using Microsoft.EntityFrameworkCore.Migrations;

namespace HappyTravel.Edo.Data.Migrations
{
    public partial class DataSeed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var sqlRegions = @"insert into public.""Regions"" (""Id"", ""Names"")
    VALUES
        (150, '{""ar"": ""أوروبا"", ""cn"": ""欧洲"", ""en"": ""Europe"", ""es"": ""Europa"", ""fr"": ""Europe"", ""ru"": ""Европа""}' ),
        (2, '{""ar"": ""أفريقيا"", ""cn"": ""非洲"", ""en"": ""Africa"", ""es"": ""África"", ""fr"": ""Afrique"", ""ru"": ""Африка""}' ),
        (19, '{""ar"": ""الأمريكتان"", ""cn"": ""美洲"", ""en"": ""Americas"", ""es"": ""América"", ""fr"": ""Amérique"", ""ru"": ""Америка""}' ),
        (142, '{""ar"": ""آسيا"", ""cn"": ""亚洲"", ""en"": ""Asia"", ""es"": ""Asia"", ""fr"": ""Asie"", ""ru"": ""Азия""}' ),
        (9, '{""ar"": ""أوقيانوسيا"", ""cn"": ""大洋洲"", ""en"": ""Oceania"", ""es"": ""Oceanía"", ""fr"": ""Océanie"", ""ru"": ""Океания""}')
    on conflict (""Id"") DO UPDATE
    SET ""Names"" = excluded.""Names"";";
            migrationBuilder.Sql(sqlRegions);

            var sqlCountries = @"insert into public.""Countries"" (""Code"", ""Names"", ""RegionId"") 
    VALUES
        ('AF', '{""ar"": ""أفغانستان"", ""cn"": ""阿富汗"", ""en"": ""Afghanistan"", ""es"": ""Afganistán"", ""fr"": ""Afghanistan"", ""ru"": ""Афганистан""}', 142),
        ('AZ', '{""ar"": ""أذربيجان"", ""cn"": ""阿塞拜疆"", ""en"": ""Azerbaijan"", ""es"": ""Azerbaiyán"", ""fr"": ""Azerbaïdjan"", ""ru"": ""Азербайджан""}', 142),
        ('BD', '{""ar"": ""بنغلاديش"", ""cn"": ""孟加拉国"", ""en"": ""Bangladesh"", ""es"": ""Bangladesh"", ""fr"": ""Bangladesh"", ""ru"": ""Бангладеш""}', 142),
        ('BI', '{""ar"": ""بوروندي"", ""cn"": ""布隆迪"", ""en"": ""Burundi"", ""es"": ""Burundi"", ""fr"": ""Burundi"", ""ru"": ""Бурунди""}', 2),
        ('BN', '{""ar"": ""بروني دار السلام"", ""cn"": ""文莱达鲁萨兰国"", ""en"": ""Brunei Darussalam"", ""es"": ""Brunei Darussalam"", ""fr"": ""Brunéi Darussalam"", ""ru"": ""Бруней-Даруссалам""}', 142),
        ('CY', '{""ar"": ""قبرص"", ""cn"": ""塞浦路斯"", ""en"": ""Cyprus"", ""es"": ""Chipre"", ""fr"": ""Chypre"", ""ru"": ""Кипр""}', 142),
        ('DM', '{""ar"": ""دومينيكا"", ""cn"": ""多米尼克"", ""en"": ""Dominica"", ""es"": ""Dominica"", ""fr"": ""Dominique"", ""ru"": ""Доминика""}', 19),
        ('DO', '{""ar"": ""الجمهورية الدومينيكية"", ""cn"": ""多米尼加"", ""en"": ""Dominican Republic"", ""es"": ""República Dominicana"", ""fr"": ""République dominicaine"", ""ru"": ""Доминиканская Республика""}', 19),
        ('GD', '{""ar"": ""غرينادا"", ""cn"": ""格林纳达"", ""en"": ""Grenada"", ""es"": ""Granada"", ""fr"": ""Grenade"", ""ru"": ""Гренада""}', 19),
        ('GE', '{""ar"": ""جورجيا"", ""cn"": ""格鲁吉亚"", ""en"": ""Georgia"", ""es"": ""Georgia"", ""fr"": ""Géorgie"", ""ru"": ""Грузия""}', 142),
        ('GP', '{""ar"": ""غوادلوب"", ""cn"": ""瓜德罗普"", ""en"": ""Guadeloupe"", ""es"": ""Guadalupe"", ""fr"": ""Guadeloupe"", ""ru"": ""Гваделупа""}', 19),
        ('HT', '{""ar"": ""هايتي"", ""cn"": ""海地"", ""en"": ""Haiti"", ""es"": ""Haití"", ""fr"": ""Haïti"", ""ru"": ""Гаити""}', 19),
        ('ID', '{""ar"": ""إندونيسيا"", ""cn"": ""印度尼西亚"", ""en"": ""Indonesia"", ""es"": ""Indonesia"", ""fr"": ""Indonésie"", ""ru"": ""Индонезия""}', 142),
        ('IL', '{""ar"": ""إسرائيل"", ""cn"": ""以色列"", ""en"": ""Israel"", ""es"": ""Israel"", ""fr"": ""Israël"", ""ru"": ""Израиль""}', 142),
        ('IN', '{""ar"": ""الهند"", ""cn"": ""印度"", ""en"": ""India"", ""es"": ""India"", ""fr"": ""Inde"", ""ru"": ""Индия""}', 142),
        ('IQ', '{""ar"": ""العراق"", ""cn"": ""伊拉克"", ""en"": ""Iraq"", ""es"": ""Iraq"", ""fr"": ""Iraq"", ""ru"": ""Ирак""}', 142),
        ('JM', '{""ar"": ""جامايكا"", ""cn"": ""牙买加"", ""en"": ""Jamaica"", ""es"": ""Jamaica"", ""fr"": ""Jamaïque"", ""ru"": ""Ямайка""}', 19),
        ('KG', '{""ar"": ""قيرغيزستان"", ""cn"": ""吉尔吉斯斯坦"", ""en"": ""Kyrgyzstan"", ""es"": ""Kirguistán"", ""fr"": ""Kirghizistan"", ""ru"": ""Кыргызстан""}', 142),
        ('KH', '{""ar"": ""كمبوديا"", ""cn"": ""柬埔寨"", ""en"": ""Cambodia"", ""es"": ""Camboya"", ""fr"": ""Cambodge"", ""ru"": ""Камбоджа""}', 142),
        ('KN', '{""ar"": ""سانت كيتس ونيفس"", ""cn"": ""圣基茨和尼维斯"", ""en"": ""Saint Kitts and Nevis"", ""es"": ""Saint Kitts y Nevis"", ""fr"": ""Saint-Kitts-et-Nevis"", ""ru"": ""Сент-Китс и Невис""}', 19),
        ('KP', '{""ar"": ""جمهورية كوريا الشعبية الديمقراطية"", ""cn"": ""朝鲜民主主义人民共和国"", ""en"": ""Democratic People''s Republic of Korea"", ""es"": ""República Popular Democrática de Corea"", ""fr"": ""République populaire démocratique de Corée"", ""ru"": ""Корейская Народно-Демократическая Республика""}', 142),
        ('KY', '{""ar"": ""جزر كايمان"", ""cn"": ""开曼群岛"", ""en"": ""Cayman Islands"", ""es"": ""Islas Caimán"", ""fr"": ""Îles Caïmanes"", ""ru"": ""Кайман острова""}', 19),
        ('KZ', '{""ar"": ""كازاخستان"", ""cn"": ""哈萨克斯坦"", ""en"": ""Kazakhstan"", ""es"": ""Kazajstán"", ""fr"": ""Kazakhstan"", ""ru"": ""Казахстан""}', 142),
        ('LA', '{""ar"": ""جمهورية لاو الديمقراطية الشعبية"", ""cn"": ""老挝人民民主共和国"", ""en"": ""Lao People''s Democratic Republic"", ""es"": ""República Democrática Popular Lao"", ""fr"": ""République démocratique populaire lao"", ""ru"": ""Лаосская Народно-Демократическая Республика""}', 142),
        ('LC', '{""ar"": ""سانت لوسيا"", ""cn"": ""圣卢西亚"", ""en"": ""Saint Lucia"", ""es"": ""Santa Lucía"", ""fr"": ""Sainte-Lucie"", ""ru"": ""Сент-Люсия""}', 19),
        ('LK', '{""ar"": ""سري لانكا"", ""cn"": ""斯里兰卡"", ""en"": ""Sri Lanka"", ""es"": ""Sri Lanka"", ""fr"": ""Sri Lanka"", ""ru"": ""Шри-Ланка""}', 142),
        ('MM', '{""ar"": ""ميانمار"", ""cn"": ""缅甸"", ""en"": ""Myanmar"", ""es"": ""Myanmar"", ""fr"": ""Myanmar"", ""ru"": ""Мьянма""}', 142),
        ('MV', '{""ar"": ""ملديف"", ""cn"": ""马尔代夫"", ""en"": ""Maldives"", ""es"": ""Maldivas"", ""fr"": ""Maldives"", ""ru"": ""Мальдивские Острова""}', 142),
        ('MY', '{""ar"": ""ماليزيا"", ""cn"": ""马来西亚"", ""en"": ""Malaysia"", ""es"": ""Malasia"", ""fr"": ""Malaisie"", ""ru"": ""Малайзия""}', 142),
        ('NP', '{""ar"": ""نيبال"", ""cn"": ""尼泊尔"", ""en"": ""Nepal"", ""es"": ""Nepal"", ""fr"": ""Népal"", ""ru"": ""Непал""}', 142),
        ('PH', '{""ar"": ""الفلبين"", ""cn"": ""菲律宾"", ""en"": ""Philippines"", ""es"": ""Filipinas"", ""fr"": ""Philippines"", ""ru"": ""Филиппины""}', 142),
        ('PK', '{""ar"": ""باكستان"", ""cn"": ""巴基斯坦"", ""en"": ""Pakistan"", ""es"": ""Pakistán"", ""fr"": ""Pakistan"", ""ru"": ""Пакистан""}', 142),
        ('SG', '{""ar"": ""سنغافورة"", ""cn"": ""新加坡"", ""en"": ""Singapore"", ""es"": ""Singapur"", ""fr"": ""Singapour"", ""ru"": ""Сингапур""}', 142),
        ('TH', '{""ar"": ""تايلند"", ""cn"": ""泰国"", ""en"": ""Thailand"", ""es"": ""Tailandia"", ""fr"": ""Thaïlande"", ""ru"": ""Таиланд""}', 142),
        ('TJ', '{""ar"": ""طاجيكستان"", ""cn"": ""塔吉克斯坦"", ""en"": ""Tajikistan"", ""es"": ""Tayikistán"", ""fr"": ""Tadjikistan"", ""ru"": ""Таджикистан""}', 142),
        ('TL', '{""ar"": ""تيمور - ليشتي"", ""cn"": ""东帝汶"", ""en"": ""Timor-Leste"", ""es"": ""Timor-Leste"", ""fr"": ""Timor-Leste"", ""ru"": ""Тимор-Лешти""}', 142),
        ('TM', '{""ar"": ""تركمانستان"", ""cn"": ""土库曼斯坦"", ""en"": ""Turkmenistan"", ""es"": ""Turkmenistán"", ""fr"": ""Turkménistan"", ""ru"": ""Туркменистан""}', 142),
        ('UZ', '{""ar"": ""أوزبكستان"", ""cn"": ""乌兹别克斯坦"", ""en"": ""Uzbekistan"", ""es"": ""Uzbekistán"", ""fr"": ""Ouzbékistan"", ""ru"": ""Узбекистан""}', 142),
        ('VN', '{""ar"": ""فييت نام"", ""cn"": ""越南"", ""en"": ""Viet Nam"", ""es"": ""Viet Nam"", ""fr"": ""Viet Nam"", ""ru"": ""Вьетнам""}', 142),
        ('BH', '{""ar"": ""البحرين"", ""cn"": ""巴林"", ""en"": ""Bahrain"", ""es"": ""Bahrein"", ""fr"": ""Bahreïn"", ""ru"": ""Бахрейн""}', 142),
        ('BT', '{""ar"": ""بوتان"", ""cn"": ""不丹"", ""en"": ""Bhutan"", ""es"": ""Bhután"", ""fr"": ""Bhoutan"", ""ru"": ""Бутан""}', 142),
        ('CN', '{""ar"": ""الصين"", ""cn"": ""中国"", ""en"": ""China"", ""es"": ""China"", ""fr"": ""Chine"", ""ru"": ""Китай""}', 142),
        ('DK', '{""ar"": ""الدانمرك"", ""cn"": ""丹麦"", ""en"": ""Denmark"", ""es"": ""Dinamarca"", ""fr"": ""Danemark"", ""ru"": ""Дания""}', 150),
        ('EE', '{""ar"": ""إستونيا"", ""cn"": ""爱沙尼亚"", ""en"": ""Estonia"", ""es"": ""Estonia"", ""fr"": ""Estonie"", ""ru"": ""Эстония""}', 150),
        ('FO', '{""ar"": ""جزر فايرو"", ""cn"": ""法罗群岛"", ""en"": ""Faroe Islands"", ""es"": ""Islas Feroe"", ""fr"": ""Îles Féroé"", ""ru"": ""Фарерские острова""}', 150),
        ('HK', '{""ar"": ""الصين، منطقة هونغ كونغ الإدارية الخاصة"", ""cn"": ""中国香港特别行政区"", ""en"": ""China, Hong Kong Special Administrative Region"", ""es"": ""China, región administrativa especial de Hong Kong"", ""fr"": ""Chine, région administrative spéciale de Hong Kong"", ""ru"": ""Китай, Специальный административный район Гонконг""}', 142),
        ('IE', '{""ar"": ""آيرلندا"", ""cn"": ""爱尔兰"", ""en"": ""Ireland"", ""es"": ""Irlanda"", ""fr"": ""Irlande"", ""ru"": ""Ирландия""}', 150),
        ('IM', '{""ar"": ""جزيرة مان"", ""cn"": ""马恩岛"", ""en"": ""Isle of Man"", ""es"": ""Isla de Man"", ""fr"": ""Île de Man"", ""ru"": ""Остров Мэн""}', 150),
        ('IS', '{""ar"": ""آيسلندا"", ""cn"": ""冰岛"", ""en"": ""Iceland"", ""es"": ""Islandia"", ""fr"": ""Islande"", ""ru"": ""Исландия""}', 150),
        ('JO', '{""ar"": ""الأردن"", ""cn"": ""约旦"", ""en"": ""Jordan"", ""es"": ""Jordania"", ""fr"": ""Jordanie"", ""ru"": ""Иордания""}', 142),
        ('JP', '{""ar"": ""اليابان"", ""cn"": ""日本"", ""en"": ""Japan"", ""es"": ""Japón"", ""fr"": ""Japon"", ""ru"": ""Япония""}', 142),
        ('KR', '{""ar"": ""جمهورية كوريا"", ""cn"": ""大韩民国"", ""en"": ""Republic of Korea"", ""es"": ""República de Corea"", ""fr"": ""République de Corée"", ""ru"": ""Республика Корея""}', 142),
        ('KW', '{""ar"": ""الكويت"", ""cn"": ""科威特"", ""en"": ""Kuwait"", ""es"": ""Kuwait"", ""fr"": ""Koweït"", ""ru"": ""Кувейт""}', 142),
        ('LB', '{""ar"": ""لبنان"", ""cn"": ""黎巴嫩"", ""en"": ""Lebanon"", ""es"": ""Líbano"", ""fr"": ""Liban"", ""ru"": ""Ливан""}', 142),
        ('LT', '{""ar"": ""ليتوانيا"", ""cn"": ""立陶宛"", ""en"": ""Lithuania"", ""es"": ""Lituania"", ""fr"": ""Lituanie"", ""ru"": ""Литва""}', 150),
        ('LV', '{""ar"": ""لاتفيا"", ""cn"": ""拉脱维亚"", ""en"": ""Latvia"", ""es"": ""Letonia"", ""fr"": ""Lettonie"", ""ru"": ""Латвия""}', 150),
        ('MF', '{""ar"": ""سانت مارتن (الجزء الفرنسي)"", ""cn"": ""圣马丁（法属）"", ""en"": ""Saint Martin (French Part)"", ""es"": ""San Martín (parte francesa)"", ""fr"": ""Saint-Martin (partie française)"", ""ru"": ""Сен-Мартен (французская часть)""}', 19),
        ('MN', '{""ar"": ""منغوليا"", ""cn"": ""蒙古"", ""en"": ""Mongolia"", ""es"": ""Mongolia"", ""fr"": ""Mongolie"", ""ru"": ""Монголия""}', 142),
        ('MO', '{""ar"": ""الصين، منطقة ماكاو الإدارية الخاصة"", ""cn"": ""中国澳门特别行政区"", ""en"": ""China, Macao Special Administrative Region"", ""es"": ""China, región administrativa especial de Macao"", ""fr"": ""Chine, région administrative spéciale de Macao"", ""ru"": ""Китай, Специальный административный район Макао""}', 142),
        ('MQ', '{""ar"": ""مارتينيك"", ""cn"": ""马提尼克"", ""en"": ""Martinique"", ""es"": ""Martinica"", ""fr"": ""Martinique"", ""ru"": ""Мартиника""}', 19),
        ('MS', '{""ar"": ""مونتسيرات"", ""cn"": ""蒙特塞拉特"", ""en"": ""Montserrat"", ""es"": ""Montserrat"", ""fr"": ""Montserrat"", ""ru"": ""Монтсеррат""}', 19),
        ('NO', '{""ar"": ""النرويج"", ""cn"": ""挪威"", ""en"": ""Norway"", ""es"": ""Noruega"", ""fr"": ""Norvège"", ""ru"": ""Норвегия""}', 150),
        ('PR', '{""ar"": ""بورتوريكو"", ""cn"": ""波多黎各"", ""en"": ""Puerto Rico"", ""es"": ""Puerto Rico"", ""fr"": ""Porto Rico"", ""ru"": ""Пуэрто-Рико""}', 19),
        ('RO', '{""ar"": ""رومانيا"", ""cn"": ""罗马尼亚"", ""en"": ""Romania"", ""es"": ""Rumania"", ""fr"": ""Roumanie"", ""ru"": ""Румыния""}', 150),
        ('RU', '{""ar"": ""الاتحاد الروسي"", ""cn"": ""俄罗斯联邦"", ""en"": ""Russian Federation"", ""es"": ""Federación de Rusia"", ""fr"": ""Fédération de Russie"", ""ru"": ""Российская Федерация""}', 150),
        ('SK', '{""ar"": ""سلوفاكيا"", ""cn"": ""斯洛伐克"", ""en"": ""Slovakia"", ""es"": ""Eslovaquia"", ""fr"": ""Slovaquie"", ""ru"": ""Словакия""}', 150),
        ('SX', '{""ar"": ""سانت مارتن (الجزء الهولندي)"", ""cn"": ""圣马丁（荷属）"", ""en"": ""Sint Maarten (Dutch part)"", ""es"": ""San Martín (parte Holandesa)"", ""fr"": ""Saint-Martin (partie néerlandaise)"", ""ru"": ""Синт-Мартен (нидерландская часть)""}', 19),
        ('TC', '{""ar"": ""جزر تركس وكايكوس"", ""cn"": ""特克斯和凯科斯群岛"", ""en"": ""Turks and Caicos Islands"", ""es"": ""Islas Turcas y Caicos"", ""fr"": ""Îles Turques-et-Caïques"", ""ru"": ""Острова Теркс и Кайкос""}', 19),
        ('TT', '{""ar"": ""ترينيداد وتوباغو"", ""cn"": ""特立尼达和多巴哥"", ""en"": ""Trinidad and Tobago"", ""es"": ""Trinidad y Tabago"", ""fr"": ""Trinité-et-Tobago"", ""ru"": ""Тринидад и Тобаго""}', 19),
        ('UA', '{""ar"": ""أوكرانيا"", ""cn"": ""乌克兰"", ""en"": ""Ukraine"", ""es"": ""Ucrania"", ""fr"": ""Ukraine"", ""ru"": ""Украина""}', 150),
        ('VC', '{""ar"": ""سانت فنسنت وجزر غرينادين"", ""cn"": ""圣文森特和格林纳丁斯"", ""en"": ""Saint Vincent and the Grenadines"", ""es"": ""San Vicente y las Granadinas"", ""fr"": ""Saint-Vincent-et-les Grenadines"", ""ru"": ""Сент-Винсент и Гренадины""}', 19),
        ('VG', '{""ar"": ""جزر فرجن البريطانية"", ""cn"": ""英属维尔京群岛"", ""en"": ""British Virgin Islands"", ""es"": ""Islas Vírgenes Británicas"", ""fr"": ""Îles Vierges britanniques"", ""ru"": ""Британские Виргинские острова""}', 19),
        ('VI', '{""ar"": ""جزر فرجن التابعة للولايات المتحدة"", ""cn"": ""美属维尔京群岛"", ""en"": ""United States Virgin Islands"", ""es"": ""Islas Vírgenes de los Estados Unidos"", ""fr"": ""Îles Vierges américaines"", ""ru"": ""Виргинские острова Соединенных Штатов""}', 19),
        ('AD', '{""ar"": ""أندورا"", ""cn"": ""安道尔"", ""en"": ""Andorra"", ""es"": ""Andorra"", ""fr"": ""Andorre"", ""ru"": ""Андорра""}', 150),
        ('AT', '{""ar"": ""النمسا"", ""cn"": ""奥地利"", ""en"": ""Austria"", ""es"": ""Austria"", ""fr"": ""Autriche"", ""ru"": ""Австрия""}', 150),
        ('AX', '{""ar"": ""جزر ألاند"", ""cn"": ""奥兰群岛"", ""en"": ""Åland Islands"", ""es"": ""Islas Åland"", ""fr"": ""Îles d’Åland"", ""ru"": ""Аландских островов""}', 150),
        ('BA', '{""ar"": ""البوسنة والهرسك"", ""cn"": ""波斯尼亚和黑塞哥维那"", ""en"": ""Bosnia and Herzegovina"", ""es"": ""Bosnia y Herzegovina"", ""fr"": ""Bosnie-Herzégovine"", ""ru"": ""Босния и Герцеговина""}', 150),
        ('BE', '{""ar"": ""بلجيكا"", ""cn"": ""比利时"", ""en"": ""Belgium"", ""es"": ""Bélgica"", ""fr"": ""Belgique"", ""ru"": ""Бельгия""}', 150),
        ('BG', '{""ar"": ""بلغاريا"", ""cn"": ""保加利亚"", ""en"": ""Bulgaria"", ""es"": ""Bulgaria"", ""fr"": ""Bulgarie"", ""ru"": ""Болгария""}', 150),
        ('BY', '{""ar"": ""بيلاروس"", ""cn"": ""白俄罗斯"", ""en"": ""Belarus"", ""es"": ""Belarús"", ""fr"": ""Bélarus"", ""ru"": ""Беларусь""}', 150),
        ('CH', '{""ar"": ""سويسرا"", ""cn"": ""瑞士"", ""en"": ""Switzerland"", ""es"": ""Suiza"", ""fr"": ""Suisse"", ""ru"": ""Швейцария""}', 150),
        ('CU', '{""ar"": ""كوبا"", ""cn"": ""古巴"", ""en"": ""Cuba"", ""es"": ""Cuba"", ""fr"": ""Cuba"", ""ru"": ""Куба""}', 19),
        ('CZ', '{""ar"": ""تشيكيا"", ""cn"": ""捷克"", ""en"": ""Czechia"", ""es"": ""Chequia"", ""fr"": ""Tchéquie"", ""ru"": ""Чехия""}', 150),
        ('DE', '{""ar"": ""ألمانيا"", ""cn"": ""德国"", ""en"": ""Germany"", ""es"": ""Alemania"", ""fr"": ""Allemagne"", ""ru"": ""Германия""}', 150),
        ('ES', '{""ar"": ""إسبانيا"", ""cn"": ""西班牙"", ""en"": ""Spain"", ""es"": ""España"", ""fr"": ""Espagne"", ""ru"": ""Испания""}', 150),
        ('FR', '{""ar"": ""فرنسا"", ""cn"": ""法国"", ""en"": ""France"", ""es"": ""Francia"", ""fr"": ""France"", ""ru"": ""Франция""}', 150),
        ('GG', '{""ar"": ""غيرنسي"", ""cn"": ""格恩西"", ""en"": ""Guernsey"", ""es"": ""Guernsey"", ""fr"": ""Guernesey"", ""ru"": ""Гернси""}', 150),
        ('GI', '{""ar"": ""جبل طارق"", ""cn"": ""直布罗陀"", ""en"": ""Gibraltar"", ""es"": ""Gibraltar"", ""fr"": ""Gibraltar"", ""ru"": ""Гибралтар""}', 150),
        ('GR', '{""ar"": ""اليونان"", ""cn"": ""希腊"", ""en"": ""Greece"", ""es"": ""Grecia"", ""fr"": ""Grèce"", ""ru"": ""Греция""}', 150),
        ('HR', '{""ar"": ""كرواتيا"", ""cn"": ""克罗地亚"", ""en"": ""Croatia"", ""es"": ""Croacia"", ""fr"": ""Croatie"", ""ru"": ""Хорватия""}', 150),
        ('HU', '{""ar"": ""هنغاريا"", ""cn"": ""匈牙利"", ""en"": ""Hungary"", ""es"": ""Hungría"", ""fr"": ""Hongrie"", ""ru"": ""Венгрия""}', 150),
        ('IT', '{""ar"": ""إيطاليا"", ""cn"": ""意大利"", ""en"": ""Italy"", ""es"": ""Italia"", ""fr"": ""Italie"", ""ru"": ""Италия""}', 150),
        ('JE', '{""ar"": ""جيرسي"", ""cn"": ""泽西"", ""en"": ""Jersey"", ""es"": ""Jersey"", ""fr"": ""Jersey"", ""ru"": ""Джерси""}', 150),
        ('LI', '{""ar"": ""ليختنشتاين"", ""cn"": ""列支敦士登"", ""en"": ""Liechtenstein"", ""es"": ""Liechtenstein"", ""fr"": ""Liechtenstein"", ""ru"": ""Лихтенштейн""}', 150),
        ('LU', '{""ar"": ""لكسمبرغ"", ""cn"": ""卢森堡"", ""en"": ""Luxembourg"", ""es"": ""Luxemburgo"", ""fr"": ""Luxembourg"", ""ru"": ""Люксембург""}', 150),
        ('MC', '{""ar"": ""موناكو"", ""cn"": ""摩纳哥"", ""en"": ""Monaco"", ""es"": ""Mónaco"", ""fr"": ""Monaco"", ""ru"": ""Монако""}', 150),
        ('ME', '{""ar"": ""الجبل الأسود"", ""cn"": ""黑山"", ""en"": ""Montenegro"", ""es"": ""Montenegro"", ""fr"": ""Monténégro"", ""ru"": ""Черногория""}', 150),
        ('MK', '{""ar"": ""مقدونيا الشمالية"", ""cn"": ""北马其顿"", ""en"": ""North Macedonia"", ""es"": ""Macedonia del Norte"", ""fr"": ""Macédoine du Nord"", ""ru"": ""Северная Македония""}', 150),
        ('MT', '{""ar"": ""مالطة"", ""cn"": ""马耳他"", ""en"": ""Malta"", ""es"": ""Malta"", ""fr"": ""Malte"", ""ru"": ""Мальта""}', 150),
        ('NL', '{""ar"": ""هولندا"", ""cn"": ""荷兰"", ""en"": ""Netherlands"", ""es"": ""Países Bajos"", ""fr"": ""Pays-Bas"", ""ru"": ""Нидерланды""}', 150),
        ('OM', '{""ar"": ""عمان"", ""cn"": ""阿曼"", ""en"": ""Oman"", ""es"": ""Omán"", ""fr"": ""Oman"", ""ru"": ""Оман""}', 142),
        ('PL', '{""ar"": ""بولندا"", ""cn"": ""波兰"", ""en"": ""Poland"", ""es"": ""Polonia"", ""fr"": ""Pologne"", ""ru"": ""Польша""}', 150),
        ('PS', '{""ar"": ""دولة فلسطين"", ""cn"": ""巴勒斯坦国"", ""en"": ""State of Palestine"", ""es"": ""Estado de Palestina"", ""fr"": ""État de Palestine"", ""ru"": ""Государство Палестина""}', 142),
        ('PT', '{""ar"": ""البرتغال"", ""cn"": ""葡萄牙"", ""en"": ""Portugal"", ""es"": ""Portugal"", ""fr"": ""Portugal"", ""ru"": ""Португалия""}', 150),
        ('QA', '{""ar"": ""قطر"", ""cn"": ""卡塔尔"", ""en"": ""Qatar"", ""es"": ""Qatar"", ""fr"": ""Qatar"", ""ru"": ""Катар""}', 142),
        ('RS', '{""ar"": ""صربيا"", ""cn"": ""塞尔维亚"", ""en"": ""Serbia"", ""es"": ""Serbia"", ""fr"": ""Serbie"", ""ru"": ""Сербия""}', 150),
        ('SA', '{""ar"": ""المملكة العربية السعودية"", ""cn"": ""沙特阿拉伯"", ""en"": ""Saudi Arabia"", ""es"": ""Arabia Saudita"", ""fr"": ""Arabie saoudite"", ""ru"": ""Саудовская Аравия""}', 142),
        ('SE', '{""ar"": ""السويد"", ""cn"": ""瑞典"", ""en"": ""Sweden"", ""es"": ""Suecia"", ""fr"": ""Suède"", ""ru"": ""Швеция""}', 150),
        ('SI', '{""ar"": ""سلوفينيا"", ""cn"": ""斯洛文尼亚"", ""en"": ""Slovenia"", ""es"": ""Eslovenia"", ""fr"": ""Slovénie"", ""ru"": ""Словения""}', 150),
        ('SJ', '{""ar"": ""جزيرتي سفالبارد وجان مايِن"", ""cn"": ""斯瓦尔巴群岛和扬马延岛"", ""en"": ""Svalbard and Jan Mayen Islands"", ""es"": ""Islas Svalbard y Jan Mayen"", ""fr"": ""Îles Svalbard-et-Jan Mayen"", ""ru"": ""Острова Свальбард и Ян-Майен""}', 150),
        ('SM', '{""ar"": ""سان مارينو"", ""cn"": ""圣马力诺"", ""en"": ""San Marino"", ""es"": ""San Marino"", ""fr"": ""Saint-Marin"", ""ru"": ""Сан-Марино""}', 150),
        ('SY', '{""ar"": ""الجمهورية العربية السورية"", ""cn"": ""阿拉伯叙利亚共和国"", ""en"": ""Syrian Arab Republic"", ""es"": ""República Árabe Siria"", ""fr"": ""République arabe syrienne"", ""ru"": ""Сирийская Арабская Республика""}', 142),
        ('TR', '{""ar"": ""تركيا"", ""cn"": ""土耳其"", ""en"": ""Turkey"", ""es"": ""Turquía"", ""fr"": ""Turquie"", ""ru"": ""Турция""}', 142),
        ('VA', '{""ar"": ""الكرسي الرسولي"", ""cn"": ""教廷"", ""en"": ""Holy See"", ""es"": ""Santa Sede"", ""fr"": ""Saint-Siège"", ""ru"": ""Святой Престол""}', 150),
        ('YE', '{""ar"": ""اليمن"", ""cn"": ""也门"", ""en"": ""Yemen"", ""es"": ""Yemen"", ""fr"": ""Yémen"", ""ru"": ""Йемен""}', 142),
        ('BJ', '{""ar"": ""بنن"", ""cn"": ""贝宁"", ""en"": ""Benin"", ""es"": ""Benin"", ""fr"": ""Bénin"", ""ru"": ""Бенин""}', 2),
        ('BS', '{""ar"": ""جزر البهاما"", ""cn"": ""巴哈马"", ""en"": ""Bahamas"", ""es"": ""Bahamas"", ""fr"": ""Bahamas"", ""ru"": ""Багамские Острова""}', 19),
        ('BW', '{""ar"": ""بوتسوانا"", ""cn"": ""博茨瓦纳"", ""en"": ""Botswana"", ""es"": ""Botswana"", ""fr"": ""Botswana"", ""ru"": ""Ботсвана""}', 2),
        ('CF', '{""ar"": ""جمهورية أفريقيا الوسطى"", ""cn"": ""中非共和国"", ""en"": ""Central African Republic"", ""es"": ""República Centroafricana"", ""fr"": ""République centrafricaine"", ""ru"": ""Центральноафриканская Республика""}', 2),
        ('CG', '{""ar"": ""الكونغو"", ""cn"": ""刚果"", ""en"": ""Congo"", ""es"": ""Congo"", ""fr"": ""Congo"", ""ru"": ""Конго""}', 2),
        ('CI', '{""ar"": ""كوت ديفوار"", ""cn"": ""科特迪瓦"", ""en"": ""Côte d’Ivoire"", ""es"": ""Côte d’Ivoire"", ""fr"": ""Côte d’Ivoire"", ""ru"": ""Кот-д''Ивуар""}', 2),
        ('CM', '{""ar"": ""الكاميرون"", ""cn"": ""喀麦隆"", ""en"": ""Cameroon"", ""es"": ""Camerún"", ""fr"": ""Cameroun"", ""ru"": ""Камерун""}', 2),
        ('CV', '{""ar"": ""كابو فيردي"", ""cn"": ""佛得角"", ""en"": ""Cabo Verde"", ""es"": ""Cabo Verde"", ""fr"": ""Cabo Verde"", ""ru"": ""Кабо-Верде""}', 2),
        ('CW', '{""ar"": ""كوراساو"", ""cn"": ""库拉索"", ""en"": ""Curaçao"", ""es"": ""Curazao"", ""fr"": ""Curaçao"", ""ru"": ""Кюрасао""}', 19),
        ('DZ', '{""ar"": ""الجزائر"", ""cn"": ""阿尔及利亚"", ""en"": ""Algeria"", ""es"": ""Argelia"", ""fr"": ""Algérie"", ""ru"": ""Алжир""}', 2),
        ('EG', '{""ar"": ""مصر"", ""cn"": ""埃及"", ""en"": ""Egypt"", ""es"": ""Egipto"", ""fr"": ""Égypte"", ""ru"": ""Египет""}', 2),
        ('EH', '{""ar"": ""الصحراء الغربية"", ""cn"": ""西撒哈拉"", ""en"": ""Western Sahara"", ""es"": ""Sáhara Occidental"", ""fr"": ""Sahara occidental"", ""ru"": ""Западная Сахара""}', 2),
        ('GA', '{""ar"": ""غابون"", ""cn"": ""加蓬"", ""en"": ""Gabon"", ""es"": ""Gabón"", ""fr"": ""Gabon"", ""ru"": ""Габон""}', 2),
        ('GH', '{""ar"": ""غانا"", ""cn"": ""加纳"", ""en"": ""Ghana"", ""es"": ""Ghana"", ""fr"": ""Ghana"", ""ru"": ""Гана""}', 2),
        ('GM', '{""ar"": ""غامبيا"", ""cn"": ""冈比亚"", ""en"": ""Gambia"", ""es"": ""Gambia"", ""fr"": ""Gambie"", ""ru"": ""Гамбия""}', 2),
        ('GN', '{""ar"": ""غينيا"", ""cn"": ""几内亚"", ""en"": ""Guinea"", ""es"": ""Guinea"", ""fr"": ""Guinée"", ""ru"": ""Гвинея""}', 2),
        ('GQ', '{""ar"": ""غينيا الاستوائية"", ""cn"": ""赤道几内亚"", ""en"": ""Equatorial Guinea"", ""es"": ""Guinea Ecuatorial"", ""fr"": ""Guinée équatoriale"", ""ru"": ""Экваториальная Гвинея""}', 2),
        ('GW', '{""ar"": ""غينيا - بيساو"", ""cn"": ""几内亚比绍"", ""en"": ""Guinea-Bissau"", ""es"": ""Guinea-Bissau"", ""fr"": ""Guinée-Bissau"", ""ru"": ""Гвинея-Бисау""}', 2),
        ('LR', '{""ar"": ""ليبريا"", ""cn"": ""利比里亚"", ""en"": ""Liberia"", ""es"": ""Liberia"", ""fr"": ""Libéria"", ""ru"": ""Либерия""}', 2),
        ('LS', '{""ar"": ""ليسوتو"", ""cn"": ""莱索托"", ""en"": ""Lesotho"", ""es"": ""Lesotho"", ""fr"": ""Lesotho"", ""ru"": ""Лесото""}', 2),
        ('LY', '{""ar"": ""ليبيا"", ""cn"": ""利比亚"", ""en"": ""Libya"", ""es"": ""Libia"", ""fr"": ""Libye"", ""ru"": ""Ливия""}', 2),
        ('MA', '{""ar"": ""المغرب"", ""cn"": ""摩洛哥"", ""en"": ""Morocco"", ""es"": ""Marruecos"", ""fr"": ""Maroc"", ""ru"": ""Марокко""}', 2),
        ('ML', '{""ar"": ""مالي"", ""cn"": ""马里"", ""en"": ""Mali"", ""es"": ""Malí"", ""fr"": ""Mali"", ""ru"": ""Мали""}', 2),
        ('MR', '{""ar"": ""موريتانيا"", ""cn"": ""毛里塔尼亚"", ""en"": ""Mauritania"", ""es"": ""Mauritania"", ""fr"": ""Mauritanie"", ""ru"": ""Мавритания""}', 2),
        ('MW', '{""ar"": ""ملاوي"", ""cn"": ""马拉维"", ""en"": ""Malawi"", ""es"": ""Malawi"", ""fr"": ""Malawi"", ""ru"": ""Малави""}', 2),
        ('NA', '{""ar"": ""ناميبيا"", ""cn"": ""纳米比亚"", ""en"": ""Namibia"", ""es"": ""Namibia"", ""fr"": ""Namibie"", ""ru"": ""Намибия""}', 2),
        ('NE', '{""ar"": ""النيجر"", ""cn"": ""尼日尔"", ""en"": ""Niger"", ""es"": ""Níger"", ""fr"": ""Niger"", ""ru"": ""Нигер""}', 2),
        ('RE', '{""ar"": ""ريونيون"", ""cn"": ""留尼汪"", ""en"": ""Réunion"", ""es"": ""Reunión"", ""fr"": ""Réunion"", ""ru"": ""Реюньон""}', 2),
        ('RW', '{""ar"": ""رواندا"", ""cn"": ""卢旺达"", ""en"": ""Rwanda"", ""es"": ""Rwanda"", ""fr"": ""Rwanda"", ""ru"": ""Руанда""}', 2),
        ('SC', '{""ar"": ""سيشيل"", ""cn"": ""塞舌尔"", ""en"": ""Seychelles"", ""es"": ""Seychelles"", ""fr"": ""Seychelles"", ""ru"": ""Сейшельские Острова""}', 2),
        ('SD', '{""ar"": ""السودان"", ""cn"": ""苏丹"", ""en"": ""Sudan"", ""es"": ""Sudán"", ""fr"": ""Soudan"", ""ru"": ""Судан""}', 2),
        ('SO', '{""ar"": ""الصومال"", ""cn"": ""索马里"", ""en"": ""Somalia"", ""es"": ""Somalia"", ""fr"": ""Somalie"", ""ru"": ""Сомали""}', 2),
        ('SS', '{""ar"": ""جنوب السودان"", ""cn"": ""南苏丹"", ""en"": ""South Sudan"", ""es"": ""Sudán del Sur"", ""fr"": ""Soudan du Sud"", ""ru"": ""Южный Судан""}', 2),
        ('ST', '{""ar"": ""سان تومي وبرينسيبي"", ""cn"": ""圣多美和普林西比"", ""en"": ""Sao Tome and Principe"", ""es"": ""Santo Tomé y Príncipe"", ""fr"": ""Sao Tomé-et-Principe"", ""ru"": ""Сан-Томе и Принсипи""}', 2),
        ('SZ', '{""ar"": ""إسواتيني"", ""cn"": ""斯威士兰"", ""en"": ""Eswatini"", ""es"": ""Eswatini"", ""fr"": ""Eswatini"", ""ru"": ""Эсватини""}', 2),
        ('TD', '{""ar"": ""تشاد"", ""cn"": ""乍得"", ""en"": ""Chad"", ""es"": ""Chad"", ""fr"": ""Tchad"", ""ru"": ""Чад""}', 2),
        ('TN', '{""ar"": ""تونس"", ""cn"": ""突尼斯"", ""en"": ""Tunisia"", ""es"": ""Túnez"", ""fr"": ""Tunisie"", ""ru"": ""Тунис""}', 2),
        ('TZ', '{""ar"": ""جمهورية تنزانيا المتحدة"", ""cn"": ""坦桑尼亚联合共和国"", ""en"": ""United Republic of Tanzania"", ""es"": ""República Unida de Tanzanía"", ""fr"": ""République-Unie de Tanzanie"", ""ru"": ""Объединенная Республика Танзания""}', 2),
        ('UG', '{""ar"": ""أوغندا"", ""cn"": ""乌干达"", ""en"": ""Uganda"", ""es"": ""Uganda"", ""fr"": ""Ouganda"", ""ru"": ""Уганда""}', 2),
        ('YT', '{""ar"": ""مايوت"", ""cn"": ""马约特"", ""en"": ""Mayotte"", ""es"": ""Mayotte"", ""fr"": ""Mayotte"", ""ru"": ""Остров Майотта""}', 2),
        ('ZA', '{""ar"": ""جنوب أفريقيا"", ""cn"": ""南非"", ""en"": ""South Africa"", ""es"": ""Sudáfrica"", ""fr"": ""Afrique du Sud"", ""ru"": ""Южная Африка""}', 2),
        ('ZM', '{""ar"": ""زامبيا"", ""cn"": ""赞比亚"", ""en"": ""Zambia"", ""es"": ""Zambia"", ""fr"": ""Zambie"", ""ru"": ""Замбия""}', 2),
        ('ZW', '{""ar"": ""زمبابوي"", ""cn"": ""津巴布韦"", ""en"": ""Zimbabwe"", ""es"": ""Zimbabwe"", ""fr"": ""Zimbabwe"", ""ru"": ""Зимбабве""}', 2),
        ('AS', '{""ar"": ""ساموا الأمريكية"", ""cn"": ""美属萨摩亚"", ""en"": ""American Samoa"", ""es"": ""Samoa Americana"", ""fr"": ""Samoa américaines"", ""ru"": ""Американское Самоа""}', 9),
        ('AU', '{""ar"": ""أستراليا"", ""cn"": ""澳大利亚"", ""en"": ""Australia"", ""es"": ""Australia"", ""fr"": ""Australie"", ""ru"": ""Австралия""}', 9),
        ('BF', '{""ar"": ""بوركينا فاسو"", ""cn"": ""布基纳法索"", ""en"": ""Burkina Faso"", ""es"": ""Burkina Faso"", ""fr"": ""Burkina Faso"", ""ru"": ""Буркина-Фасо""}', 2),
        ('BL', '{""ar"": ""سان بارتليمي"", ""cn"": ""圣巴泰勒米"", ""en"": ""Saint Barthélemy"", ""es"": ""San Barthélemy"", ""fr"": ""Saint-Barthélemy"", ""ru"": ""Сен-Бартелеми""}', 19),
        ('BZ', '{""ar"": ""بليز"", ""cn"": ""伯利兹"", ""en"": ""Belize"", ""es"": ""Belice"", ""fr"": ""Belize"", ""ru"": ""Белиз""}', 19),
        ('CR', '{""ar"": ""كوستاريكا"", ""cn"": ""哥斯达黎加"", ""en"": ""Costa Rica"", ""es"": ""Costa Rica"", ""fr"": ""Costa Rica"", ""ru"": ""Коста-Рика""}', 19),
        ('CX', '{""ar"": ""جزيرة عيد الميلاد"", ""cn"": ""圣诞岛"", ""en"": ""Christmas Island"", ""es"": ""Isla Christmas"", ""fr"": ""Île Christmas"", ""ru"": ""остров Рождества""}', 9),
        ('DJ', '{""ar"": ""جيبوتي"", ""cn"": ""吉布提"", ""en"": ""Djibouti"", ""es"": ""Djibouti"", ""fr"": ""Djibouti"", ""ru"": ""Джибути""}', 2),
        ('ER', '{""ar"": ""إريتريا"", ""cn"": ""厄立特里亚"", ""en"": ""Eritrea"", ""es"": ""Eritrea"", ""fr"": ""Érythrée"", ""ru"": ""Эритрея""}', 2),
        ('ET', '{""ar"": ""إثيوبيا"", ""cn"": ""埃塞俄比亚"", ""en"": ""Ethiopia"", ""es"": ""Etiopía"", ""fr"": ""Éthiopie"", ""ru"": ""Эфиопия""}', 2),
        ('FK', '{""ar"": ""جزر فوكلاند (مالفيناس)"", ""cn"": ""福克兰群岛（马尔维纳斯）"", ""en"": ""Falkland Islands (Malvinas)"", ""es"": ""Islas Malvinas (Falkland)"", ""fr"": ""Îles Falkland (Malvinas)"", ""ru"": ""Фолклендские (Мальвинские) острова""}', 19),
        ('GF', '{""ar"": ""غيانا الفرنسية"", ""cn"": ""法属圭亚那"", ""en"": ""French Guiana"", ""es"": ""Guayana Francesa"", ""fr"": ""Guyane française"", ""ru"": ""Французская Гвиана""}', 19),
        ('GS', '{""ar"": ""جورجيا الجنوبية وجزر ساندويتش الجنوبية"", ""cn"": ""南乔治亚岛和南桑德韦奇岛"", ""en"": ""South Georgia and the South Sandwich Islands"", ""es"": ""Georgia del Sur y las Islas Sandwich del Sur"", ""fr"": ""Géorgie du Sud-et-les Îles Sandwich du Sud"", ""ru"": ""Южная Джорджия и Южные Сандвичевы острова""}', 19),
        ('GT', '{""ar"": ""غواتيمالا"", ""cn"": ""危地马拉"", ""en"": ""Guatemala"", ""es"": ""Guatemala"", ""fr"": ""Guatemala"", ""ru"": ""Гватемала""}', 19),
        ('GY', '{""ar"": ""غيانا"", ""cn"": ""圭亚那"", ""en"": ""Guyana"", ""es"": ""Guyana"", ""fr"": ""Guyana"", ""ru"": ""Гайана""}', 19),
        ('HN', '{""ar"": ""هندوراس"", ""cn"": ""洪都拉斯"", ""en"": ""Honduras"", ""es"": ""Honduras"", ""fr"": ""Honduras"", ""ru"": ""Гондурас""}', 19),
        ('IO', '{""ar"": ""المحيط الهندي الإقليم البريطاني في"", ""cn"": ""英属印度洋领土"", ""en"": ""British Indian Ocean Territory"", ""es"": ""Territorio Británico del Océano Índico"", ""fr"": ""Territoire britannique de l''océan Indien"", ""ru"": ""Британская территория в Индийском океане""}', 2),
        ('KE', '{""ar"": ""كينيا"", ""cn"": ""肯尼亚"", ""en"": ""Kenya"", ""es"": ""Kenya"", ""fr"": ""Kenya"", ""ru"": ""Кения""}', 2),
        ('KM', '{""ar"": ""جزر القمر"", ""cn"": ""科摩罗"", ""en"": ""Comoros"", ""es"": ""Comoras"", ""fr"": ""Comores"", ""ru"": ""Коморские Острова""}', 2),
        ('MG', '{""ar"": ""مدغشقر"", ""cn"": ""马达加斯加"", ""en"": ""Madagascar"", ""es"": ""Madagascar"", ""fr"": ""Madagascar"", ""ru"": ""Мадагаскар""}', 2),
        ('MU', '{""ar"": ""موريشيوس"", ""cn"": ""毛里求斯"", ""en"": ""Mauritius"", ""es"": ""Mauricio"", ""fr"": ""Maurice"", ""ru"": ""Маврикий""}', 2),
        ('MX', '{""ar"": ""المكسيك"", ""cn"": ""墨西哥"", ""en"": ""Mexico"", ""es"": ""México"", ""fr"": ""Mexique"", ""ru"": ""Мексика""}', 19),
        ('MZ', '{""ar"": ""موزامبيق"", ""cn"": ""莫桑比克"", ""en"": ""Mozambique"", ""es"": ""Mozambique"", ""fr"": ""Mozambique"", ""ru"": ""Мозамбик""}', 2),
        ('NG', '{""ar"": ""نيجيريا"", ""cn"": ""尼日利亚"", ""en"": ""Nigeria"", ""es"": ""Nigeria"", ""fr"": ""Nigéria"", ""ru"": ""Нигерия""}', 2),
        ('NI', '{""ar"": ""نيكاراغوا"", ""cn"": ""尼加拉瓜"", ""en"": ""Nicaragua"", ""es"": ""Nicaragua"", ""fr"": ""Nicaragua"", ""ru"": ""Никарагуа""}', 19),
        ('PA', '{""ar"": ""بنما"", ""cn"": ""巴拿马"", ""en"": ""Panama"", ""es"": ""Panamá"", ""fr"": ""Panama"", ""ru"": ""Панама""}', 19),
        ('PE', '{""ar"": ""بيرو"", ""cn"": ""秘鲁"", ""en"": ""Peru"", ""es"": ""Perú"", ""fr"": ""Pérou"", ""ru"": ""Перу""}', 19),
        ('PY', '{""ar"": ""باراغواي"", ""cn"": ""巴拉圭"", ""en"": ""Paraguay"", ""es"": ""Paraguay"", ""fr"": ""Paraguay"", ""ru"": ""Парагвай""}', 19),
        ('SH', '{""ar"": ""سانت هيلانة"", ""cn"": ""圣赫勒拿"", ""en"": ""Saint Helena"", ""es"": ""Santa Elena"", ""fr"": ""Sainte-Hélène"", ""ru"": ""Остров Святой Елены""}', 2),
        ('SL', '{""ar"": ""سيراليون"", ""cn"": ""塞拉利昂"", ""en"": ""Sierra Leone"", ""es"": ""Sierra Leona"", ""fr"": ""Sierra Leone"", ""ru"": ""Сьерра-Леоне""}', 2),
        ('SN', '{""ar"": ""السنغال"", ""cn"": ""塞内加尔"", ""en"": ""Senegal"", ""es"": ""Senegal"", ""fr"": ""Sénégal"", ""ru"": ""Сенегал""}', 2),
        ('SR', '{""ar"": ""سورينام"", ""cn"": ""苏里南"", ""en"": ""Suriname"", ""es"": ""Suriname"", ""fr"": ""Suriname"", ""ru"": ""Суринам""}', 19),
        ('SV', '{""ar"": ""السلفادور"", ""cn"": ""萨尔瓦多"", ""en"": ""El Salvador"", ""es"": ""El Salvador"", ""fr"": ""El Salvador"", ""ru"": ""Сальвадор""}', 19),
        ('TF', '{""ar"": ""الأراضي الفرنسية الجنوبية الجنوبية"", ""cn"": ""法属南方领地"", ""en"": ""French Southern Territories"", ""es"": ""Territorio de las Tierras Australes Francesas"", ""fr"": ""Terres australes françaises"", ""ru"": ""Южные земли (французская заморская территория)""}', 2),
        ('TG', '{""ar"": ""توغو"", ""cn"": ""多哥"", ""en"": ""Togo"", ""es"": ""Togo"", ""fr"": ""Togo"", ""ru"": ""Того""}', 2),
        ('UY', '{""ar"": ""أوروغواي"", ""cn"": ""乌拉圭"", ""en"": ""Uruguay"", ""es"": ""Uruguay"", ""fr"": ""Uruguay"", ""ru"": ""Уругвай""}', 19),
        ('VE', '{""ar"": ""فنزويلا (جمهورية - البوليفارية)"", ""cn"": ""委内瑞拉玻利瓦尔共和国"", ""en"": ""Venezuela (Bolivarian Republic of)"", ""es"": ""Venezuela (República Bolivariana de)"", ""fr"": ""Venezuela (République bolivarienne du)"", ""ru"": ""Венесуэла (Боливарианская Республика)""}', 19),
        ('AI', '{""ar"": ""أنغويلا"", ""cn"": ""安圭拉"", ""en"": ""Anguilla"", ""es"": ""Anguila"", ""fr"": ""Anguilla"", ""ru"": ""Ангилья""}', 19),
        ('AR', '{""ar"": ""الأرجنتين"", ""cn"": ""阿根廷"", ""en"": ""Argentina"", ""es"": ""Argentina"", ""fr"": ""Argentine"", ""ru"": ""Аргентина""}', 19),
        ('AW', '{""ar"": ""أروبا"", ""cn"": ""阿鲁巴"", ""en"": ""Aruba"", ""es"": ""Aruba"", ""fr"": ""Aruba"", ""ru"": ""Аруба""}', 19),
        ('BM', '{""ar"": ""برمودا"", ""cn"": ""百慕大"", ""en"": ""Bermuda"", ""es"": ""Bermuda"", ""fr"": ""Bermudes"", ""ru"": ""Бермудские острова""}', 19),
        ('BQ', '{""ar"": ""بونير وسانت يوستاشيوس وسابا"", ""cn"": ""博纳尔，圣俄斯塔休斯和萨巴"", ""en"": ""Bonaire, Sint Eustatius and Saba"", ""es"": ""Bonaire, San Eustaquio y Saba"", ""fr"": ""Bonaire, Saint-Eustache et Saba"", ""ru"": ""Бонайре, Синт-Эстатиус и Саба""}', 19),
        ('BR', '{""ar"": ""البرازيل"", ""cn"": ""巴西"", ""en"": ""Brazil"", ""es"": ""Brasil"", ""fr"": ""Brésil"", ""ru"": ""Бразилия""}', 19),
        ('BV', '{""ar"": ""جزيرة بوفيت"", ""cn"": ""布维岛"", ""en"": ""Bouvet Island"", ""es"": ""Isla Bouvet"", ""fr"": ""Île Bouvet"", ""ru"": ""Остров Буве""}', 19),
        ('CA', '{""ar"": ""كندا"", ""cn"": ""加拿大"", ""en"": ""Canada"", ""es"": ""Canadá"", ""fr"": ""Canada"", ""ru"": ""Канада""}', 19),
        ('CK', '{""ar"": ""جزر كوك"", ""cn"": ""库克群岛"", ""en"": ""Cook Islands"", ""es"": ""Islas Cook"", ""fr"": ""Îles Cook"", ""ru"": ""Острова Кука""}', 9),
        ('CL', '{""ar"": ""شيلي"", ""cn"": ""智利"", ""en"": ""Chile"", ""es"": ""Chile"", ""fr"": ""Chili"", ""ru"": ""Чили""}', 19),
        ('CO', '{""ar"": ""كولومبيا"", ""cn"": ""哥伦比亚"", ""en"": ""Colombia"", ""es"": ""Colombia"", ""fr"": ""Colombie"", ""ru"": ""Колумбия""}', 19),
        ('EC', '{""ar"": ""إكوادور"", ""cn"": ""厄瓜多尔"", ""en"": ""Ecuador"", ""es"": ""Ecuador"", ""fr"": ""Équateur"", ""ru"": ""Эквадор""}', 19),
        ('FJ', '{""ar"": ""فيجي"", ""cn"": ""斐济"", ""en"": ""Fiji"", ""es"": ""Fiji"", ""fr"": ""Fidji"", ""ru"": ""Фиджи""}', 9),
        ('FM', '{""ar"": ""ميكرونيزيا (ولايات - الموحدة)"", ""cn"": ""密克罗尼西亚联邦"", ""en"": ""Micronesia (Federated States of)"", ""es"": ""Micronesia (Estados Federados de)"", ""fr"": ""Micronésie (États fédérés de)"", ""ru"": ""Микронезия (Федеративные Штаты)""}', 9),
        ('GL', '{""ar"": ""غرينلند"", ""cn"": ""格陵兰"", ""en"": ""Greenland"", ""es"": ""Groenlandia"", ""fr"": ""Groenland"", ""ru"": ""Гренландия""}', 19),
        ('GU', '{""ar"": ""غوام"", ""cn"": ""关岛"", ""en"": ""Guam"", ""es"": ""Guam"", ""fr"": ""Guam"", ""ru"": ""Гуам""}', 9),
        ('HM', '{""ar"": ""جزيرة هيرد وجزر ماكدونالد"", ""cn"": ""赫德岛和麦克唐纳岛"", ""en"": ""Heard Island and McDonald Islands"", ""es"": ""Islas Heard y McDonald"", ""fr"": ""Île Heard-et-Îles MacDonald"", ""ru"": ""Остров Херд и острова Макдональд""}', 9),
        ('KI', '{""ar"": ""كيريباس"", ""cn"": ""基里巴斯"", ""en"": ""Kiribati"", ""es"": ""Kiribati"", ""fr"": ""Kiribati"", ""ru"": ""Кирибати""}', 9),
        ('MH', '{""ar"": ""جزر مارشال"", ""cn"": ""马绍尔群岛"", ""en"": ""Marshall Islands"", ""es"": ""Islas Marshall"", ""fr"": ""Îles Marshall"", ""ru"": ""Маршалловы Острова""}', 9),
        ('MP', '{""ar"": ""جزر ماريانا الشمالية"", ""cn"": ""北马里亚纳群岛"", ""en"": ""Northern Mariana Islands"", ""es"": ""Islas Marianas Septentrionales"", ""fr"": ""Îles Mariannes du Nord"", ""ru"": ""Северные Марианские острова""}', 9),
        ('NC', '{""ar"": ""كاليدونيا الجديدة"", ""cn"": ""新喀里多尼亚"", ""en"": ""New Caledonia"", ""es"": ""Nueva Caledonia"", ""fr"": ""Nouvelle-Calédonie"", ""ru"": ""Новая Каледония""}', 9),
        ('NF', '{""ar"": ""جزيرة نورفولك"", ""cn"": ""诺福克岛"", ""en"": ""Norfolk Island"", ""es"": ""Isla Norfolk"", ""fr"": ""Île Norfolk"", ""ru"": ""Остров Норфолк""}', 9),
        ('NR', '{""ar"": ""ناورو"", ""cn"": ""瑙鲁"", ""en"": ""Nauru"", ""es"": ""Nauru"", ""fr"": ""Nauru"", ""ru"": ""Науру""}', 9),
        ('NU', '{""ar"": ""نيوي"", ""cn"": ""纽埃"", ""en"": ""Niue"", ""es"": ""Niue"", ""fr"": ""Nioué"", ""ru"": ""Ниуэ""}', 9),
        ('NZ', '{""ar"": ""نيوزيلندا"", ""cn"": ""新西兰"", ""en"": ""New Zealand"", ""es"": ""Nueva Zelandia"", ""fr"": ""Nouvelle-Zélande"", ""ru"": ""Новая Зеландия""}', 9),
        ('PF', '{""ar"": ""بولينيزيا الفرنسية"", ""cn"": ""法属波利尼西亚"", ""en"": ""French Polynesia"", ""es"": ""Polinesia Francesa"", ""fr"": ""Polynésie française"", ""ru"": ""Французская Полинезия""}', 9),
        ('PG', '{""ar"": ""بابوا غينيا الجديدة"", ""cn"": ""巴布亚新几内亚"", ""en"": ""Papua New Guinea"", ""es"": ""Papua Nueva Guinea"", ""fr"": ""Papouasie-Nouvelle-Guinée"", ""ru"": ""Папуа-Новая Гвинея""}', 9),
        ('PM', '{""ar"": ""سان بيير وميكلون"", ""cn"": ""圣皮埃尔和密克隆"", ""en"": ""Saint Pierre and Miquelon"", ""es"": ""San Pedro y Miquelón"", ""fr"": ""Saint-Pierre-et-Miquelon"", ""ru"": ""Сен-Пьер и Микелон""}', 19),
        ('PN', '{""ar"": ""بيتكرن"", ""cn"": ""皮特凯恩"", ""en"": ""Pitcairn"", ""es"": ""Pitcairn"", ""fr"": ""Pitcairn"", ""ru"": ""Питкэрн""}', 9),
        ('PW', '{""ar"": ""بالاو"", ""cn"": ""帕劳"", ""en"": ""Palau"", ""es"": ""Palau"", ""fr"": ""Palaos"", ""ru"": ""Палау""}', 9),
        ('SB', '{""ar"": ""جزر سليمان"", ""cn"": ""所罗门群岛"", ""en"": ""Solomon Islands"", ""es"": ""Islas Salomón"", ""fr"": ""Îles Salomon"", ""ru"": ""Соломоновы Острова""}', 9),
        ('TO', '{""ar"": ""تونغا"", ""cn"": ""汤加"", ""en"": ""Tonga"", ""es"": ""Tonga"", ""fr"": ""Tonga"", ""ru"": ""Тонга""}', 9),
        ('TV', '{""ar"": ""توفالو"", ""cn"": ""图瓦卢"", ""en"": ""Tuvalu"", ""es"": ""Tuvalu"", ""fr"": ""Tuvalu"", ""ru"": ""Тувалу""}', 9),
        ('US', '{""ar"": ""الولايات المتحدة الأمريكية"", ""cn"": ""美利坚合众国"", ""en"": ""United States of America"", ""es"": ""Estados Unidos de América"", ""fr"": ""États-Unis d’Amérique"", ""ru"": ""Соединенные Штаты Америки""}', 19),
        ('VU', '{""ar"": ""فانواتو"", ""cn"": ""瓦努阿图"", ""en"": ""Vanuatu"", ""es"": ""Vanuatu"", ""fr"": ""Vanuatu"", ""ru"": ""Вануату""}', 9),
        ('WF', '{""ar"": ""جزر واليس وفوتونا"", ""cn"": ""瓦利斯群岛和富图纳群岛"", ""en"": ""Wallis and Futuna Islands"", ""es"": ""Islas Wallis y Futuna"", ""fr"": ""Îles Wallis-et-Futuna"", ""ru"": ""Острова Уоллис и Футуна""}', 9),
        ('WS', '{""ar"": ""ساموا"", ""cn"": ""萨摩亚"", ""en"": ""Samoa"", ""es"": ""Samoa"", ""fr"": ""Samoa"", ""ru"": ""Самоа""}', 9),
        ('–', '{""ar"": ""سارك"", ""cn"": ""萨克"", ""en"": ""Sark"", ""es"": ""Sark"", ""fr"": ""Sercq"", ""ru"": ""Сарк""}', 150),
        ('AE', '{""ar"": ""الإمارات العربية المتحدة"", ""cn"": ""阿拉伯联合酋长国"", ""en"": ""United Arab Emirates"", ""es"": ""Emiratos Árabes Unidos"", ""fr"": ""Émirats arabes unis"", ""ru"": ""Объединенные Арабские Эмираты""}', 142),
        ('AG', '{""ar"": ""أنتيغوا وبربودا"", ""cn"": ""安提瓜和巴布达"", ""en"": ""Antigua and Barbuda"", ""es"": ""Antigua y Barbuda"", ""fr"": ""Antigua-et-Barbuda"", ""ru"": ""Антигуа и Барбуда""}', 19),
        ('AL', '{""ar"": ""ألبانيا"", ""cn"": ""阿尔巴尼亚"", ""en"": ""Albania"", ""es"": ""Albania"", ""fr"": ""Albanie"", ""ru"": ""Албания""}', 150),
        ('AM', '{""ar"": ""أرمينيا"", ""cn"": ""亚美尼亚"", ""en"": ""Armenia"", ""es"": ""Armenia"", ""fr"": ""Arménie"", ""ru"": ""Армения""}', 142),
        ('AO', '{""ar"": ""أنغولا"", ""cn"": ""安哥拉"", ""en"": ""Angola"", ""es"": ""Angola"", ""fr"": ""Angola"", ""ru"": ""Ангола""}', 2),
        ('BB', '{""ar"": ""بربادوس"", ""cn"": ""巴巴多斯"", ""en"": ""Barbados"", ""es"": ""Barbados"", ""fr"": ""Barbade"", ""ru"": ""Барбадос""}', 19),
        ('BO', '{""ar"": ""بوليفيا (دولة - المتعددة القوميات)"", ""cn"": ""多民族玻利维亚国"", ""en"": ""Bolivia (Plurinational State of)"", ""es"": ""Bolivia (Estado Plurinacional de)"", ""fr"": ""Bolivie (État plurinational de)"", ""ru"": ""Боливия (Многонациональное Государство)""}', 19),
        ('CC', '{""ar"": ""جزر كوكس (كيلينغ)"", ""cn"": ""科科斯（基林）群岛"", ""en"": ""Cocos (Keeling) Islands"", ""es"": ""Islas Cocos (Keeling)"", ""fr"": ""Îles des Cocos (Keeling)"", ""ru"": ""Кокосовых (Килинг) островов""}', 9),
        ('CD', '{""ar"": ""جمهورية الكونغو الديمقراطية"", ""cn"": ""刚果民主共和国"", ""en"": ""Democratic Republic of the Congo"", ""es"": ""República Democrática del Congo"", ""fr"": ""République démocratique du Congo"", ""ru"": ""Демократическая Республика Конго""}', 2),
        ('FI', '{""ar"": ""فنلندا"", ""cn"": ""芬兰"", ""en"": ""Finland"", ""es"": ""Finlandia"", ""fr"": ""Finlande"", ""ru"": ""Финляндия""}', 150),
        ('GB', '{""ar"": ""المملكة المتحدة لبريطانيا العظمى وآيرلندا الشمالية"", ""cn"": ""大不列颠及北爱尔兰联合王国"", ""en"": ""United Kingdom of Great Britain and Northern Ireland"", ""es"": ""Reino Unido de Gran Bretaña e Irlanda del Norte"", ""fr"": ""Royaume-Uni de Grande-Bretagne et d’Irlande du Nord"", ""ru"": ""Соединенное Королевство Великобритании и Северной Ирландии""}', 150),
        ('IR', '{""ar"": ""إيران (جمهورية - الإسلامية)"", ""cn"": ""伊朗伊斯兰共和国"", ""en"": ""Iran (Islamic Republic of)"", ""es"": ""Irán (República Islámica del)"", ""fr"": ""Iran (République islamique d’)"", ""ru"": ""Иран (Исламская Республика)""}', 142),
        ('MD', '{""ar"": ""جمهورية مولدوفا"", ""cn"": ""摩尔多瓦共和国"", ""en"": ""Republic of Moldova"", ""es"": ""República de Moldova"", ""fr"": ""République de Moldova"", ""ru"": ""Республика Молдова""}', 150),
        ('TK', '{""ar"": ""توكيلاو"", ""cn"": ""托克劳"", ""en"": ""Tokelau"", ""es"": ""Tokelau"", ""fr"": ""Tokélaou"", ""ru"": ""Токелау""}', 9),
        ('UM', '{""ar"": ""نائية التابعة للولايات المتحدة"", ""cn"": ""美国本土外小岛屿"", ""en"": ""United States Minor Outlying Islands"", ""es"": ""Islas menores alejadas de Estados Unidos"", ""fr"": ""Îles mineures éloignées des États-Unis"", ""ru"": ""Внешние малые острова Соединенных Штатов""}', 9)
    on conflict (""Code"") DO UPDATE
    SET (""RegionId"", ""Names"") = (excluded.""RegionId"", excluded.""Names"");";
            migrationBuilder.Sql(sqlCountries);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
