// <auto-generated />
using HappyTravel.Edo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HappyTravel.Edo.Data.Migrations
{
    [DbContext(typeof(EdoContext))]
    [Migration("20190608125226_RegionsAndCountries")]
    partial class RegionsAndCountries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HappyTravel.Edo.Data.Locations.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RegionId");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "BI",
                            Names = "{\"ar\":\"بوروندي\",\"cn\":\"Burundi\",\"en\":\"布隆迪\",\"es\":\"Burundi\",\"fr\":\"Burundi\",\"ru\":\"Бурунди\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "BJ",
                            Names = "{\"ar\":\"بنن\",\"cn\":\"Benin\",\"en\":\"贝宁\",\"es\":\"Benin\",\"fr\":\"Bénin\",\"ru\":\"Бенин\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "CI",
                            Names = "{\"ar\":\"كوت ديفوار\",\"cn\":\"Côte d’Ivoire\",\"en\":\"科特迪瓦\",\"es\":\"Côte d’Ivoire\",\"fr\":\"Côte d’Ivoire\",\"ru\":\"Кот-д'Ивуар\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "CV",
                            Names = "{\"ar\":\"كابو فيردي\",\"cn\":\"Cabo Verde\",\"en\":\"佛得角\",\"es\":\"Cabo Verde\",\"fr\":\"Cabo Verde\",\"ru\":\"Кабо-Верде\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "GH",
                            Names = "{\"ar\":\"غانا\",\"cn\":\"Ghana\",\"en\":\"加纳\",\"es\":\"Ghana\",\"fr\":\"Ghana\",\"ru\":\"Гана\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "GN",
                            Names = "{\"ar\":\"غينيا\",\"cn\":\"Guinea\",\"en\":\"几内亚\",\"es\":\"Guinea\",\"fr\":\"Guinée\",\"ru\":\"Гвинея\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "GM",
                            Names = "{\"ar\":\"غامبيا\",\"cn\":\"Gambia\",\"en\":\"冈比亚\",\"es\":\"Gambia\",\"fr\":\"Gambie\",\"ru\":\"Гамбия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "GW",
                            Names = "{\"ar\":\"غينيا - بيساو\",\"cn\":\"Guinea-Bissau\",\"en\":\"几内亚比绍\",\"es\":\"Guinea-Bissau\",\"fr\":\"Guinée-Bissau\",\"ru\":\"Гвинея-Бисау\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "LR",
                            Names = "{\"ar\":\"ليبريا\",\"cn\":\"Liberia\",\"en\":\"利比里亚\",\"es\":\"Liberia\",\"fr\":\"Libéria\",\"ru\":\"Либерия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ML",
                            Names = "{\"ar\":\"مالي\",\"cn\":\"Mali\",\"en\":\"马里\",\"es\":\"Malí\",\"fr\":\"Mali\",\"ru\":\"Мали\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "MR",
                            Names = "{\"ar\":\"موريتانيا\",\"cn\":\"Mauritania\",\"en\":\"毛里塔尼亚\",\"es\":\"Mauritania\",\"fr\":\"Mauritanie\",\"ru\":\"Мавритания\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "NE",
                            Names = "{\"ar\":\"النيجر\",\"cn\":\"Niger\",\"en\":\"尼日尔\",\"es\":\"Níger\",\"fr\":\"Niger\",\"ru\":\"Нигер\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "NG",
                            Names = "{\"ar\":\"نيجيريا\",\"cn\":\"Nigeria\",\"en\":\"尼日利亚\",\"es\":\"Nigeria\",\"fr\":\"Nigéria\",\"ru\":\"Нигерия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SN",
                            Names = "{\"ar\":\"السنغال\",\"cn\":\"Senegal\",\"en\":\"塞内加尔\",\"es\":\"Senegal\",\"fr\":\"Sénégal\",\"ru\":\"Сенегал\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SH",
                            Names = "{\"ar\":\"سانت هيلانة\",\"cn\":\"Saint Helena\",\"en\":\"圣赫勒拿\",\"es\":\"Santa Elena\",\"fr\":\"Sainte-Hélène\",\"ru\":\"Остров Святой Елены\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SL",
                            Names = "{\"ar\":\"سيراليون\",\"cn\":\"Sierra Leone\",\"en\":\"塞拉利昂\",\"es\":\"Sierra Leona\",\"fr\":\"Sierra Leone\",\"ru\":\"Сьерра-Леоне\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "TG",
                            Names = "{\"ar\":\"توغو\",\"cn\":\"Togo\",\"en\":\"多哥\",\"es\":\"Togo\",\"fr\":\"Togo\",\"ru\":\"Того\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "AO",
                            Names = "{\"ar\":\"أنغولا\",\"cn\":\"Angola\",\"en\":\"安哥拉\",\"es\":\"Angola\",\"fr\":\"Angola\",\"ru\":\"Ангола\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "TF",
                            Names = "{\"ar\":\"الأراضي الفرنسية الجنوبية الجنوبية\",\"cn\":\"French Southern Territories\",\"en\":\"法属南方领地\",\"es\":\"Territorio de las Tierras Australes Francesas\",\"fr\":\"Terres australes françaises\",\"ru\":\"Южные земли (французская заморская территория)\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "BF",
                            Names = "{\"ar\":\"بوركينا فاسو\",\"cn\":\"Burkina Faso\",\"en\":\"布基纳法索\",\"es\":\"Burkina Faso\",\"fr\":\"Burkina Faso\",\"ru\":\"Буркина-Фасо\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "KM",
                            Names = "{\"ar\":\"جزر القمر\",\"cn\":\"Comoros\",\"en\":\"科摩罗\",\"es\":\"Comoras\",\"fr\":\"Comores\",\"ru\":\"Коморские Острова\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "DJ",
                            Names = "{\"ar\":\"جيبوتي\",\"cn\":\"Djibouti\",\"en\":\"吉布提\",\"es\":\"Djibouti\",\"fr\":\"Djibouti\",\"ru\":\"Джибути\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ER",
                            Names = "{\"ar\":\"إريتريا\",\"cn\":\"Eritrea\",\"en\":\"厄立特里亚\",\"es\":\"Eritrea\",\"fr\":\"Érythrée\",\"ru\":\"Эритрея\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ET",
                            Names = "{\"ar\":\"إثيوبيا\",\"cn\":\"Ethiopia\",\"en\":\"埃塞俄比亚\",\"es\":\"Etiopía\",\"fr\":\"Éthiopie\",\"ru\":\"Эфиопия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "IO",
                            Names = "{\"ar\":\"المحيط الهندي الإقليم البريطاني في\",\"cn\":\"British Indian Ocean Territory\",\"en\":\"英属印度洋领土\",\"es\":\"Territorio Británico del Océano Índico\",\"fr\":\"Territoire britannique de l'océan Indien\",\"ru\":\"Британская территория в Индийском океане\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "KE",
                            Names = "{\"ar\":\"كينيا\",\"cn\":\"Kenya\",\"en\":\"肯尼亚\",\"es\":\"Kenya\",\"fr\":\"Kenya\",\"ru\":\"Кения\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "MG",
                            Names = "{\"ar\":\"مدغشقر\",\"cn\":\"Madagascar\",\"en\":\"马达加斯加\",\"es\":\"Madagascar\",\"fr\":\"Madagascar\",\"ru\":\"Мадагаскар\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "MZ",
                            Names = "{\"ar\":\"موزامبيق\",\"cn\":\"Mozambique\",\"en\":\"莫桑比克\",\"es\":\"Mozambique\",\"fr\":\"Mozambique\",\"ru\":\"Мозамбик\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "MU",
                            Names = "{\"ar\":\"موريشيوس\",\"cn\":\"Mauritius\",\"en\":\"毛里求斯\",\"es\":\"Mauricio\",\"fr\":\"Maurice\",\"ru\":\"Маврикий\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "MW",
                            Names = "{\"ar\":\"ملاوي\",\"cn\":\"Malawi\",\"en\":\"马拉维\",\"es\":\"Malawi\",\"fr\":\"Malawi\",\"ru\":\"Малави\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "YT",
                            Names = "{\"ar\":\"مايوت\",\"cn\":\"Mayotte\",\"en\":\"马约特\",\"es\":\"Mayotte\",\"fr\":\"Mayotte\",\"ru\":\"Остров Майотта\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "RE",
                            Names = "{\"ar\":\"ريونيون\",\"cn\":\"Réunion\",\"en\":\"留尼汪\",\"es\":\"Reunión\",\"fr\":\"Réunion\",\"ru\":\"Реюньон\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "RW",
                            Names = "{\"ar\":\"رواندا\",\"cn\":\"Rwanda\",\"en\":\"卢旺达\",\"es\":\"Rwanda\",\"fr\":\"Rwanda\",\"ru\":\"Руанда\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SO",
                            Names = "{\"ar\":\"الصومال\",\"cn\":\"Somalia\",\"en\":\"索马里\",\"es\":\"Somalia\",\"fr\":\"Somalie\",\"ru\":\"Сомали\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SS",
                            Names = "{\"ar\":\"جنوب السودان\",\"cn\":\"South Sudan\",\"en\":\"南苏丹\",\"es\":\"Sudán del Sur\",\"fr\":\"Soudan du Sud\",\"ru\":\"Южный Судан\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SC",
                            Names = "{\"ar\":\"سيشيل\",\"cn\":\"Seychelles\",\"en\":\"塞舌尔\",\"es\":\"Seychelles\",\"fr\":\"Seychelles\",\"ru\":\"Сейшельские Острова\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "TZ",
                            Names = "{\"ar\":\"جمهورية تنزانيا المتحدة\",\"cn\":\"United Republic of Tanzania\",\"en\":\"坦桑尼亚联合共和国\",\"es\":\"República Unida de Tanzanía\",\"fr\":\"République-Unie de Tanzanie\",\"ru\":\"Объединенная Республика Танзания\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "UG",
                            Names = "{\"ar\":\"أوغندا\",\"cn\":\"Uganda\",\"en\":\"乌干达\",\"es\":\"Uganda\",\"fr\":\"Ouganda\",\"ru\":\"Уганда\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ZM",
                            Names = "{\"ar\":\"زامبيا\",\"cn\":\"Zambia\",\"en\":\"赞比亚\",\"es\":\"Zambia\",\"fr\":\"Zambie\",\"ru\":\"Замбия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ZW",
                            Names = "{\"ar\":\"زمبابوي\",\"cn\":\"Zimbabwe\",\"en\":\"津巴布韦\",\"es\":\"Zimbabwe\",\"fr\":\"Zimbabwe\",\"ru\":\"Зимбабве\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "DZ",
                            Names = "{\"ar\":\"الجزائر\",\"cn\":\"Algeria\",\"en\":\"阿尔及利亚\",\"es\":\"Argelia\",\"fr\":\"Algérie\",\"ru\":\"Алжир\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "EG",
                            Names = "{\"ar\":\"مصر\",\"cn\":\"Egypt\",\"en\":\"埃及\",\"es\":\"Egipto\",\"fr\":\"Égypte\",\"ru\":\"Египет\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "EH",
                            Names = "{\"ar\":\"الصحراء الغربية\",\"cn\":\"Western Sahara\",\"en\":\"西撒哈拉\",\"es\":\"Sáhara Occidental\",\"fr\":\"Sahara occidental\",\"ru\":\"Западная Сахара\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "LY",
                            Names = "{\"ar\":\"ليبيا\",\"cn\":\"Libya\",\"en\":\"利比亚\",\"es\":\"Libia\",\"fr\":\"Libye\",\"ru\":\"Ливия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "MA",
                            Names = "{\"ar\":\"المغرب\",\"cn\":\"Morocco\",\"en\":\"摩洛哥\",\"es\":\"Marruecos\",\"fr\":\"Maroc\",\"ru\":\"Марокко\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SD",
                            Names = "{\"ar\":\"السودان\",\"cn\":\"Sudan\",\"en\":\"苏丹\",\"es\":\"Sudán\",\"fr\":\"Soudan\",\"ru\":\"Судан\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "TN",
                            Names = "{\"ar\":\"تونس\",\"cn\":\"Tunisia\",\"en\":\"突尼斯\",\"es\":\"Túnez\",\"fr\":\"Tunisie\",\"ru\":\"Тунис\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "CF",
                            Names = "{\"ar\":\"جمهورية أفريقيا الوسطى\",\"cn\":\"Central African Republic\",\"en\":\"中非共和国\",\"es\":\"República Centroafricana\",\"fr\":\"République centrafricaine\",\"ru\":\"Центральноафриканская Республика\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "CM",
                            Names = "{\"ar\":\"الكاميرون\",\"cn\":\"Cameroon\",\"en\":\"喀麦隆\",\"es\":\"Camerún\",\"fr\":\"Cameroun\",\"ru\":\"Камерун\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "CD",
                            Names = "{\"ar\":\"جمهورية الكونغو الديمقراطية\",\"cn\":\"Democratic Republic of the Congo\",\"en\":\"刚果民主共和国\",\"es\":\"República Democrática del Congo\",\"fr\":\"République démocratique du Congo\",\"ru\":\"Демократическая Республика Конго\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "CG",
                            Names = "{\"ar\":\"الكونغو\",\"cn\":\"Congo\",\"en\":\"刚果\",\"es\":\"Congo\",\"fr\":\"Congo\",\"ru\":\"Конго\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "GA",
                            Names = "{\"ar\":\"غابون\",\"cn\":\"Gabon\",\"en\":\"加蓬\",\"es\":\"Gabón\",\"fr\":\"Gabon\",\"ru\":\"Габон\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "GQ",
                            Names = "{\"ar\":\"غينيا الاستوائية\",\"cn\":\"Equatorial Guinea\",\"en\":\"赤道几内亚\",\"es\":\"Guinea Ecuatorial\",\"fr\":\"Guinée équatoriale\",\"ru\":\"Экваториальная Гвинея\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ST",
                            Names = "{\"ar\":\"سان تومي وبرينسيبي\",\"cn\":\"Sao Tome and Principe\",\"en\":\"圣多美和普林西比\",\"es\":\"Santo Tomé y Príncipe\",\"fr\":\"Sao Tomé-et-Principe\",\"ru\":\"Сан-Томе и Принсипи\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "TD",
                            Names = "{\"ar\":\"تشاد\",\"cn\":\"Chad\",\"en\":\"乍得\",\"es\":\"Chad\",\"fr\":\"Tchad\",\"ru\":\"Чад\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "BW",
                            Names = "{\"ar\":\"بوتسوانا\",\"cn\":\"Botswana\",\"en\":\"博茨瓦纳\",\"es\":\"Botswana\",\"fr\":\"Botswana\",\"ru\":\"Ботсвана\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "LS",
                            Names = "{\"ar\":\"ليسوتو\",\"cn\":\"Lesotho\",\"en\":\"莱索托\",\"es\":\"Lesotho\",\"fr\":\"Lesotho\",\"ru\":\"Лесото\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "NA",
                            Names = "{\"ar\":\"ناميبيا\",\"cn\":\"Namibia\",\"en\":\"纳米比亚\",\"es\":\"Namibia\",\"fr\":\"Namibie\",\"ru\":\"Намибия\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "SZ",
                            Names = "{\"ar\":\"إسواتيني\",\"cn\":\"Eswatini\",\"en\":\"斯威士兰\",\"es\":\"Eswatini\",\"fr\":\"Eswatini\",\"ru\":\"Эсватини\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "ZA",
                            Names = "{\"ar\":\"جنوب أفريقيا\",\"cn\":\"South Africa\",\"en\":\"南非\",\"es\":\"Sudáfrica\",\"fr\":\"Afrique du Sud\",\"ru\":\"Южная Африка\"}",
                            RegionId = 2
                        },
                        new
                        {
                            Code = "AS",
                            Names = "{\"ar\":\"ساموا الأمريكية\",\"cn\":\"American Samoa\",\"en\":\"美属萨摩亚\",\"es\":\"Samoa Americana\",\"fr\":\"Samoa américaines\",\"ru\":\"Американское Самоа\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "AU",
                            Names = "{\"ar\":\"أستراليا\",\"cn\":\"Australia\",\"en\":\"澳大利亚\",\"es\":\"Australia\",\"fr\":\"Australie\",\"ru\":\"Австралия\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "CC",
                            Names = "{\"ar\":\"جزر كوكس (كيلينغ)\",\"cn\":\"Cocos (Keeling) Islands\",\"en\":\"科科斯（基林）群岛\",\"es\":\"Islas Cocos (Keeling)\",\"fr\":\"Îles des Cocos (Keeling)\",\"ru\":\"Кокосовых (Килинг) островов\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "CX",
                            Names = "{\"ar\":\"جزيرة عيد الميلاد\",\"cn\":\"Christmas Island\",\"en\":\"圣诞岛\",\"es\":\"Isla Christmas\",\"fr\":\"Île Christmas\",\"ru\":\"остров Рождества\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "HM",
                            Names = "{\"ar\":\"جزيرة هيرد وجزر ماكدونالد\",\"cn\":\"Heard Island and McDonald Islands\",\"en\":\"赫德岛和麦克唐纳岛\",\"es\":\"Islas Heard y McDonald\",\"fr\":\"Île Heard-et-Îles MacDonald\",\"ru\":\"Остров Херд и острова Макдональд\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "NF",
                            Names = "{\"ar\":\"جزيرة نورفولك\",\"cn\":\"Norfolk Island\",\"en\":\"诺福克岛\",\"es\":\"Isla Norfolk\",\"fr\":\"Île Norfolk\",\"ru\":\"Остров Норфолк\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "NZ",
                            Names = "{\"ar\":\"نيوزيلندا\",\"cn\":\"New Zealand\",\"en\":\"新西兰\",\"es\":\"Nueva Zelandia\",\"fr\":\"Nouvelle-Zélande\",\"ru\":\"Новая Зеландия\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "FJ",
                            Names = "{\"ar\":\"فيجي\",\"cn\":\"Fiji\",\"en\":\"斐济\",\"es\":\"Fiji\",\"fr\":\"Fidji\",\"ru\":\"Фиджи\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "NC",
                            Names = "{\"ar\":\"كاليدونيا الجديدة\",\"cn\":\"New Caledonia\",\"en\":\"新喀里多尼亚\",\"es\":\"Nueva Caledonia\",\"fr\":\"Nouvelle-Calédonie\",\"ru\":\"Новая Каледония\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "PG",
                            Names = "{\"ar\":\"بابوا غينيا الجديدة\",\"cn\":\"Papua New Guinea\",\"en\":\"巴布亚新几内亚\",\"es\":\"Papua Nueva Guinea\",\"fr\":\"Papouasie-Nouvelle-Guinée\",\"ru\":\"Папуа-Новая Гвинея\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "SB",
                            Names = "{\"ar\":\"جزر سليمان\",\"cn\":\"Solomon Islands\",\"en\":\"所罗门群岛\",\"es\":\"Islas Salomón\",\"fr\":\"Îles Salomon\",\"ru\":\"Соломоновы Острова\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "VU",
                            Names = "{\"ar\":\"فانواتو\",\"cn\":\"Vanuatu\",\"en\":\"瓦努阿图\",\"es\":\"Vanuatu\",\"fr\":\"Vanuatu\",\"ru\":\"Вануату\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "FM",
                            Names = "{\"ar\":\"ميكرونيزيا (ولايات - الموحدة)\",\"cn\":\"Micronesia (Federated States of)\",\"en\":\"密克罗尼西亚联邦\",\"es\":\"Micronesia (Estados Federados de)\",\"fr\":\"Micronésie (États fédérés de)\",\"ru\":\"Микронезия (Федеративные Штаты)\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "GU",
                            Names = "{\"ar\":\"غوام\",\"cn\":\"Guam\",\"en\":\"关岛\",\"es\":\"Guam\",\"fr\":\"Guam\",\"ru\":\"Гуам\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "KI",
                            Names = "{\"ar\":\"كيريباس\",\"cn\":\"Kiribati\",\"en\":\"基里巴斯\",\"es\":\"Kiribati\",\"fr\":\"Kiribati\",\"ru\":\"Кирибати\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "MH",
                            Names = "{\"ar\":\"جزر مارشال\",\"cn\":\"Marshall Islands\",\"en\":\"马绍尔群岛\",\"es\":\"Islas Marshall\",\"fr\":\"Îles Marshall\",\"ru\":\"Маршалловы Острова\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "MP",
                            Names = "{\"ar\":\"جزر ماريانا الشمالية\",\"cn\":\"Northern Mariana Islands\",\"en\":\"北马里亚纳群岛\",\"es\":\"Islas Marianas Septentrionales\",\"fr\":\"Îles Mariannes du Nord\",\"ru\":\"Северные Марианские острова\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "NR",
                            Names = "{\"ar\":\"ناورو\",\"cn\":\"Nauru\",\"en\":\"瑙鲁\",\"es\":\"Nauru\",\"fr\":\"Nauru\",\"ru\":\"Науру\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "PW",
                            Names = "{\"ar\":\"بالاو\",\"cn\":\"Palau\",\"en\":\"帕劳\",\"es\":\"Palau\",\"fr\":\"Palaos\",\"ru\":\"Палау\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "UM",
                            Names = "{\"ar\":\"نائية التابعة للولايات المتحدة\",\"cn\":\"United States Minor Outlying Islands\",\"en\":\"美国本土外小岛屿\",\"es\":\"Islas menores alejadas de Estados Unidos\",\"fr\":\"Îles mineures éloignées des États-Unis\",\"ru\":\"Внешние малые острова Соединенных Штатов\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "CK",
                            Names = "{\"ar\":\"جزر كوك\",\"cn\":\"Cook Islands\",\"en\":\"库克群岛\",\"es\":\"Islas Cook\",\"fr\":\"Îles Cook\",\"ru\":\"Острова Кука\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "NU",
                            Names = "{\"ar\":\"نيوي\",\"cn\":\"Niue\",\"en\":\"纽埃\",\"es\":\"Niue\",\"fr\":\"Nioué\",\"ru\":\"Ниуэ\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "PN",
                            Names = "{\"ar\":\"بيتكرن\",\"cn\":\"Pitcairn\",\"en\":\"皮特凯恩\",\"es\":\"Pitcairn\",\"fr\":\"Pitcairn\",\"ru\":\"Питкэрн\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "PF",
                            Names = "{\"ar\":\"بولينيزيا الفرنسية\",\"cn\":\"French Polynesia\",\"en\":\"法属波利尼西亚\",\"es\":\"Polinesia Francesa\",\"fr\":\"Polynésie française\",\"ru\":\"Французская Полинезия\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "TK",
                            Names = "{\"ar\":\"توكيلاو\",\"cn\":\"Tokelau\",\"en\":\"托克劳\",\"es\":\"Tokelau\",\"fr\":\"Tokélaou\",\"ru\":\"Токелау\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "TO",
                            Names = "{\"ar\":\"تونغا\",\"cn\":\"Tonga\",\"en\":\"汤加\",\"es\":\"Tonga\",\"fr\":\"Tonga\",\"ru\":\"Тонга\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "TV",
                            Names = "{\"ar\":\"توفالو\",\"cn\":\"Tuvalu\",\"en\":\"图瓦卢\",\"es\":\"Tuvalu\",\"fr\":\"Tuvalu\",\"ru\":\"Тувалу\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "WF",
                            Names = "{\"ar\":\"جزر واليس وفوتونا\",\"cn\":\"Wallis and Futuna Islands\",\"en\":\"瓦利斯群岛和富图纳群岛\",\"es\":\"Islas Wallis y Futuna\",\"fr\":\"Îles Wallis-et-Futuna\",\"ru\":\"Острова Уоллис и Футуна\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "WS",
                            Names = "{\"ar\":\"ساموا\",\"cn\":\"Samoa\",\"en\":\"萨摩亚\",\"es\":\"Samoa\",\"fr\":\"Samoa\",\"ru\":\"Самоа\"}",
                            RegionId = 9
                        },
                        new
                        {
                            Code = "AG",
                            Names = "{\"ar\":\"أنتيغوا وبربودا\",\"cn\":\"Antigua and Barbuda\",\"en\":\"安提瓜和巴布达\",\"es\":\"Antigua y Barbuda\",\"fr\":\"Antigua-et-Barbuda\",\"ru\":\"Антигуа и Барбуда\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BO",
                            Names = "{\"ar\":\"بوليفيا (دولة - المتعددة القوميات)\",\"cn\":\"Bolivia (Plurinational State of)\",\"en\":\"多民族玻利维亚国\",\"es\":\"Bolivia (Estado Plurinacional de)\",\"fr\":\"Bolivie (État plurinational de)\",\"ru\":\"Боливия (Многонациональное Государство)\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BR",
                            Names = "{\"ar\":\"البرازيل\",\"cn\":\"Brazil\",\"en\":\"巴西\",\"es\":\"Brasil\",\"fr\":\"Brésil\",\"ru\":\"Бразилия\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BV",
                            Names = "{\"ar\":\"جزيرة بوفيت\",\"cn\":\"Bouvet Island\",\"en\":\"布维岛\",\"es\":\"Isla Bouvet\",\"fr\":\"Île Bouvet\",\"ru\":\"Остров Буве\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "CL",
                            Names = "{\"ar\":\"شيلي\",\"cn\":\"Chile\",\"en\":\"智利\",\"es\":\"Chile\",\"fr\":\"Chili\",\"ru\":\"Чили\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "CO",
                            Names = "{\"ar\":\"كولومبيا\",\"cn\":\"Colombia\",\"en\":\"哥伦比亚\",\"es\":\"Colombia\",\"fr\":\"Colombie\",\"ru\":\"Колумбия\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "EC",
                            Names = "{\"ar\":\"إكوادور\",\"cn\":\"Ecuador\",\"en\":\"厄瓜多尔\",\"es\":\"Ecuador\",\"fr\":\"Équateur\",\"ru\":\"Эквадор\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "FK",
                            Names = "{\"ar\":\"جزر فوكلاند (مالفيناس)\",\"cn\":\"Falkland Islands (Malvinas)\",\"en\":\"福克兰群岛（马尔维纳斯）\",\"es\":\"Islas Malvinas (Falkland)\",\"fr\":\"Îles Falkland (Malvinas)\",\"ru\":\"Фолклендские (Мальвинские) острова\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GF",
                            Names = "{\"ar\":\"غيانا الفرنسية\",\"cn\":\"French Guiana\",\"en\":\"法属圭亚那\",\"es\":\"Guayana Francesa\",\"fr\":\"Guyane française\",\"ru\":\"Французская Гвиана\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GY",
                            Names = "{\"ar\":\"غيانا\",\"cn\":\"Guyana\",\"en\":\"圭亚那\",\"es\":\"Guyana\",\"fr\":\"Guyana\",\"ru\":\"Гайана\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "PE",
                            Names = "{\"ar\":\"بيرو\",\"cn\":\"Peru\",\"en\":\"秘鲁\",\"es\":\"Perú\",\"fr\":\"Pérou\",\"ru\":\"Перу\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "PY",
                            Names = "{\"ar\":\"باراغواي\",\"cn\":\"Paraguay\",\"en\":\"巴拉圭\",\"es\":\"Paraguay\",\"fr\":\"Paraguay\",\"ru\":\"Парагвай\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GS",
                            Names = "{\"ar\":\"جورجيا الجنوبية وجزر ساندويتش الجنوبية\",\"cn\":\"South Georgia and the South Sandwich Islands\",\"en\":\"南乔治亚岛和南桑德韦奇岛\",\"es\":\"Georgia del Sur y las Islas Sandwich del Sur\",\"fr\":\"Géorgie du Sud-et-les Îles Sandwich du Sud\",\"ru\":\"Южная Джорджия и Южные Сандвичевы острова\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "SR",
                            Names = "{\"ar\":\"سورينام\",\"cn\":\"Suriname\",\"en\":\"苏里南\",\"es\":\"Suriname\",\"fr\":\"Suriname\",\"ru\":\"Суринам\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "UY",
                            Names = "{\"ar\":\"أوروغواي\",\"cn\":\"Uruguay\",\"en\":\"乌拉圭\",\"es\":\"Uruguay\",\"fr\":\"Uruguay\",\"ru\":\"Уругвай\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "VE",
                            Names = "{\"ar\":\"فنزويلا (جمهورية - البوليفارية)\",\"cn\":\"Venezuela (Bolivarian Republic of)\",\"en\":\"委内瑞拉玻利瓦尔共和国\",\"es\":\"Venezuela (República Bolivariana de)\",\"fr\":\"Venezuela (République bolivarienne du)\",\"ru\":\"Венесуэла (Боливарианская Республика)\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BZ",
                            Names = "{\"ar\":\"بليز\",\"cn\":\"Belize\",\"en\":\"伯利兹\",\"es\":\"Belice\",\"fr\":\"Belize\",\"ru\":\"Белиз\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "CR",
                            Names = "{\"ar\":\"كوستاريكا\",\"cn\":\"Costa Rica\",\"en\":\"哥斯达黎加\",\"es\":\"Costa Rica\",\"fr\":\"Costa Rica\",\"ru\":\"Коста-Рика\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GT",
                            Names = "{\"ar\":\"غواتيمالا\",\"cn\":\"Guatemala\",\"en\":\"危地马拉\",\"es\":\"Guatemala\",\"fr\":\"Guatemala\",\"ru\":\"Гватемала\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "HN",
                            Names = "{\"ar\":\"هندوراس\",\"cn\":\"Honduras\",\"en\":\"洪都拉斯\",\"es\":\"Honduras\",\"fr\":\"Honduras\",\"ru\":\"Гондурас\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "MX",
                            Names = "{\"ar\":\"المكسيك\",\"cn\":\"Mexico\",\"en\":\"墨西哥\",\"es\":\"México\",\"fr\":\"Mexique\",\"ru\":\"Мексика\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "NI",
                            Names = "{\"ar\":\"نيكاراغوا\",\"cn\":\"Nicaragua\",\"en\":\"尼加拉瓜\",\"es\":\"Nicaragua\",\"fr\":\"Nicaragua\",\"ru\":\"Никарагуа\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "PA",
                            Names = "{\"ar\":\"بنما\",\"cn\":\"Panama\",\"en\":\"巴拿马\",\"es\":\"Panamá\",\"fr\":\"Panama\",\"ru\":\"Панама\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "SV",
                            Names = "{\"ar\":\"السلفادور\",\"cn\":\"El Salvador\",\"en\":\"萨尔瓦多\",\"es\":\"El Salvador\",\"fr\":\"El Salvador\",\"ru\":\"Сальвадор\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "AW",
                            Names = "{\"ar\":\"أروبا\",\"cn\":\"Aruba\",\"en\":\"阿鲁巴\",\"es\":\"Aruba\",\"fr\":\"Aruba\",\"ru\":\"Аруба\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "AI",
                            Names = "{\"ar\":\"أنغويلا\",\"cn\":\"Anguilla\",\"en\":\"安圭拉\",\"es\":\"Anguila\",\"fr\":\"Anguilla\",\"ru\":\"Ангилья\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "AR",
                            Names = "{\"ar\":\"الأرجنتين\",\"cn\":\"Argentina\",\"en\":\"阿根廷\",\"es\":\"Argentina\",\"fr\":\"Argentine\",\"ru\":\"Аргентина\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BQ",
                            Names = "{\"ar\":\"بونير وسانت يوستاشيوس وسابا\",\"cn\":\"Bonaire, Sint Eustatius and Saba\",\"en\":\"博纳尔，圣俄斯塔休斯和萨巴\",\"es\":\"Bonaire, San Eustaquio y Saba\",\"fr\":\"Bonaire, Saint-Eustache et Saba\",\"ru\":\"Бонайре, Синт-Эстатиус и Саба\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BM",
                            Names = "{\"ar\":\"برمودا\",\"cn\":\"Bermuda\",\"en\":\"百慕大\",\"es\":\"Bermuda\",\"fr\":\"Bermudes\",\"ru\":\"Бермудские острова\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "CA",
                            Names = "{\"ar\":\"كندا\",\"cn\":\"Canada\",\"en\":\"加拿大\",\"es\":\"Canadá\",\"fr\":\"Canada\",\"ru\":\"Канада\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GL",
                            Names = "{\"ar\":\"غرينلند\",\"cn\":\"Greenland\",\"en\":\"格陵兰\",\"es\":\"Groenlandia\",\"fr\":\"Groenland\",\"ru\":\"Гренландия\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "PM",
                            Names = "{\"ar\":\"سان بيير وميكلون\",\"cn\":\"Saint Pierre and Miquelon\",\"en\":\"圣皮埃尔和密克隆\",\"es\":\"San Pedro y Miquelón\",\"fr\":\"Saint-Pierre-et-Miquelon\",\"ru\":\"Сен-Пьер и Микелон\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "US",
                            Names = "{\"ar\":\"الولايات المتحدة الأمريكية\",\"cn\":\"United States of America\",\"en\":\"美利坚合众国\",\"es\":\"Estados Unidos de América\",\"fr\":\"États-Unis d’Amérique\",\"ru\":\"Соединенные Штаты Америки\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BS",
                            Names = "{\"ar\":\"جزر البهاما\",\"cn\":\"Bahamas\",\"en\":\"巴哈马\",\"es\":\"Bahamas\",\"fr\":\"Bahamas\",\"ru\":\"Багамские Острова\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BL",
                            Names = "{\"ar\":\"سان بارتليمي\",\"cn\":\"Saint Barthélemy\",\"en\":\"圣巴泰勒米\",\"es\":\"San Barthélemy\",\"fr\":\"Saint-Barthélemy\",\"ru\":\"Сен-Бартелеми\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "BB",
                            Names = "{\"ar\":\"بربادوس\",\"cn\":\"Barbados\",\"en\":\"巴巴多斯\",\"es\":\"Barbados\",\"fr\":\"Barbade\",\"ru\":\"Барбадос\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "CU",
                            Names = "{\"ar\":\"كوبا\",\"cn\":\"Cuba\",\"en\":\"古巴\",\"es\":\"Cuba\",\"fr\":\"Cuba\",\"ru\":\"Куба\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "CW",
                            Names = "{\"ar\":\"كوراساو\",\"cn\":\"Curaçao\",\"en\":\"库拉索\",\"es\":\"Curazao\",\"fr\":\"Curaçao\",\"ru\":\"Кюрасао\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "KY",
                            Names = "{\"ar\":\"جزر كايمان\",\"cn\":\"Cayman Islands\",\"en\":\"开曼群岛\",\"es\":\"Islas Caimán\",\"fr\":\"Îles Caïmanes\",\"ru\":\"Кайман острова\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "DM",
                            Names = "{\"ar\":\"دومينيكا\",\"cn\":\"Dominica\",\"en\":\"多米尼克\",\"es\":\"Dominica\",\"fr\":\"Dominique\",\"ru\":\"Доминика\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "DO",
                            Names = "{\"ar\":\"الجمهورية الدومينيكية\",\"cn\":\"Dominican Republic\",\"en\":\"多米尼加\",\"es\":\"República Dominicana\",\"fr\":\"République dominicaine\",\"ru\":\"Доминиканская Республика\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GP",
                            Names = "{\"ar\":\"غوادلوب\",\"cn\":\"Guadeloupe\",\"en\":\"瓜德罗普\",\"es\":\"Guadalupe\",\"fr\":\"Guadeloupe\",\"ru\":\"Гваделупа\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "GD",
                            Names = "{\"ar\":\"غرينادا\",\"cn\":\"Grenada\",\"en\":\"格林纳达\",\"es\":\"Granada\",\"fr\":\"Grenade\",\"ru\":\"Гренада\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "HT",
                            Names = "{\"ar\":\"هايتي\",\"cn\":\"Haiti\",\"en\":\"海地\",\"es\":\"Haití\",\"fr\":\"Haïti\",\"ru\":\"Гаити\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "JM",
                            Names = "{\"ar\":\"جامايكا\",\"cn\":\"Jamaica\",\"en\":\"牙买加\",\"es\":\"Jamaica\",\"fr\":\"Jamaïque\",\"ru\":\"Ямайка\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "KN",
                            Names = "{\"ar\":\"سانت كيتس ونيفس\",\"cn\":\"Saint Kitts and Nevis\",\"en\":\"圣基茨和尼维斯\",\"es\":\"Saint Kitts y Nevis\",\"fr\":\"Saint-Kitts-et-Nevis\",\"ru\":\"Сент-Китс и Невис\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "LC",
                            Names = "{\"ar\":\"سانت لوسيا\",\"cn\":\"Saint Lucia\",\"en\":\"圣卢西亚\",\"es\":\"Santa Lucía\",\"fr\":\"Sainte-Lucie\",\"ru\":\"Сент-Люсия\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "MF",
                            Names = "{\"ar\":\"سانت مارتن (الجزء الفرنسي)\",\"cn\":\"Saint Martin (French Part)\",\"en\":\"圣马丁（法属）\",\"es\":\"San Martín (parte francesa)\",\"fr\":\"Saint-Martin (partie française)\",\"ru\":\"Сен-Мартен (французская часть)\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "MS",
                            Names = "{\"ar\":\"مونتسيرات\",\"cn\":\"Montserrat\",\"en\":\"蒙特塞拉特\",\"es\":\"Montserrat\",\"fr\":\"Montserrat\",\"ru\":\"Монтсеррат\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "MQ",
                            Names = "{\"ar\":\"مارتينيك\",\"cn\":\"Martinique\",\"en\":\"马提尼克\",\"es\":\"Martinica\",\"fr\":\"Martinique\",\"ru\":\"Мартиника\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "PR",
                            Names = "{\"ar\":\"بورتوريكو\",\"cn\":\"Puerto Rico\",\"en\":\"波多黎各\",\"es\":\"Puerto Rico\",\"fr\":\"Porto Rico\",\"ru\":\"Пуэрто-Рико\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "SX",
                            Names = "{\"ar\":\"سانت مارتن (الجزء الهولندي)\",\"cn\":\"Sint Maarten (Dutch part)\",\"en\":\"圣马丁（荷属）\",\"es\":\"San Martín (parte Holandesa)\",\"fr\":\"Saint-Martin (partie néerlandaise)\",\"ru\":\"Синт-Мартен (нидерландская часть)\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "TC",
                            Names = "{\"ar\":\"جزر تركس وكايكوس\",\"cn\":\"Turks and Caicos Islands\",\"en\":\"特克斯和凯科斯群岛\",\"es\":\"Islas Turcas y Caicos\",\"fr\":\"Îles Turques-et-Caïques\",\"ru\":\"Острова Теркс и Кайкос\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "TT",
                            Names = "{\"ar\":\"ترينيداد وتوباغو\",\"cn\":\"Trinidad and Tobago\",\"en\":\"特立尼达和多巴哥\",\"es\":\"Trinidad y Tabago\",\"fr\":\"Trinité-et-Tobago\",\"ru\":\"Тринидад и Тобаго\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "VC",
                            Names = "{\"ar\":\"سانت فنسنت وجزر غرينادين\",\"cn\":\"Saint Vincent and the Grenadines\",\"en\":\"圣文森特和格林纳丁斯\",\"es\":\"San Vicente y las Granadinas\",\"fr\":\"Saint-Vincent-et-les Grenadines\",\"ru\":\"Сент-Винсент и Гренадины\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "VG",
                            Names = "{\"ar\":\"جزر فرجن البريطانية\",\"cn\":\"British Virgin Islands\",\"en\":\"英属维尔京群岛\",\"es\":\"Islas Vírgenes Británicas\",\"fr\":\"Îles Vierges britanniques\",\"ru\":\"Британские Виргинские острова\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "VI",
                            Names = "{\"ar\":\"جزر فرجن التابعة للولايات المتحدة\",\"cn\":\"United States Virgin Islands\",\"en\":\"美属维尔京群岛\",\"es\":\"Islas Vírgenes de los Estados Unidos\",\"fr\":\"Îles Vierges américaines\",\"ru\":\"Виргинские острова Соединенных Штатов\"}",
                            RegionId = 19
                        },
                        new
                        {
                            Code = "AM",
                            Names = "{\"ar\":\"أرمينيا\",\"cn\":\"Armenia\",\"en\":\"亚美尼亚\",\"es\":\"Armenia\",\"fr\":\"Arménie\",\"ru\":\"Армения\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "BH",
                            Names = "{\"ar\":\"البحرين\",\"cn\":\"Bahrain\",\"en\":\"巴林\",\"es\":\"Bahrein\",\"fr\":\"Bahreïn\",\"ru\":\"Бахрейн\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "CN",
                            Names = "{\"ar\":\"الصين\",\"cn\":\"China\",\"en\":\"中国\",\"es\":\"China\",\"fr\":\"Chine\",\"ru\":\"Китай\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "HK",
                            Names = "{\"ar\":\"الصين، منطقة هونغ كونغ الإدارية الخاصة\",\"cn\":\"China, Hong Kong Special Administrative Region\",\"en\":\"中国香港特别行政区\",\"es\":\"China, región administrativa especial de Hong Kong\",\"fr\":\"Chine, région administrative spéciale de Hong Kong\",\"ru\":\"Китай, Специальный административный район Гонконг\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "JP",
                            Names = "{\"ar\":\"اليابان\",\"cn\":\"Japan\",\"en\":\"日本\",\"es\":\"Japón\",\"fr\":\"Japon\",\"ru\":\"Япония\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "KR",
                            Names = "{\"ar\":\"جمهورية كوريا\",\"cn\":\"Republic of Korea\",\"en\":\"大韩民国\",\"es\":\"República de Corea\",\"fr\":\"République de Corée\",\"ru\":\"Республика Корея\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "MO",
                            Names = "{\"ar\":\"الصين، منطقة ماكاو الإدارية الخاصة\",\"cn\":\"China, Macao Special Administrative Region\",\"en\":\"中国澳门特别行政区\",\"es\":\"China, región administrativa especial de Macao\",\"fr\":\"Chine, région administrative spéciale de Macao\",\"ru\":\"Китай, Специальный административный район Макао\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "MN",
                            Names = "{\"ar\":\"منغوليا\",\"cn\":\"Mongolia\",\"en\":\"蒙古\",\"es\":\"Mongolia\",\"fr\":\"Mongolie\",\"ru\":\"Монголия\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "KP",
                            Names = "{\"ar\":\"جمهورية كوريا الشعبية الديمقراطية\",\"cn\":\"Democratic People's Republic of Korea\",\"en\":\"朝鲜民主主义人民共和国\",\"es\":\"República Popular Democrática de Corea\",\"fr\":\"République populaire démocratique de Corée\",\"ru\":\"Корейская Народно-Демократическая Республика\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "BT",
                            Names = "{\"ar\":\"بوتان\",\"cn\":\"Bhutan\",\"en\":\"不丹\",\"es\":\"Bhután\",\"fr\":\"Bhoutan\",\"ru\":\"Бутан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "IN",
                            Names = "{\"ar\":\"الهند\",\"cn\":\"India\",\"en\":\"印度\",\"es\":\"India\",\"fr\":\"Inde\",\"ru\":\"Индия\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "IR",
                            Names = "{\"ar\":\"إيران (جمهورية - الإسلامية)\",\"cn\":\"Iran (Islamic Republic of)\",\"en\":\"伊朗伊斯兰共和国\",\"es\":\"Irán (República Islámica del)\",\"fr\":\"Iran (République islamique d’)\",\"ru\":\"Иран (Исламская Республика)\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "LK",
                            Names = "{\"ar\":\"سري لانكا\",\"cn\":\"Sri Lanka\",\"en\":\"斯里兰卡\",\"es\":\"Sri Lanka\",\"fr\":\"Sri Lanka\",\"ru\":\"Шри-Ланка\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "MV",
                            Names = "{\"ar\":\"ملديف\",\"cn\":\"Maldives\",\"en\":\"马尔代夫\",\"es\":\"Maldivas\",\"fr\":\"Maldives\",\"ru\":\"Мальдивские Острова\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "NP",
                            Names = "{\"ar\":\"نيبال\",\"cn\":\"Nepal\",\"en\":\"尼泊尔\",\"es\":\"Nepal\",\"fr\":\"Népal\",\"ru\":\"Непал\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "PK",
                            Names = "{\"ar\":\"باكستان\",\"cn\":\"Pakistan\",\"en\":\"巴基斯坦\",\"es\":\"Pakistán\",\"fr\":\"Pakistan\",\"ru\":\"Пакистан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "BN",
                            Names = "{\"ar\":\"بروني دار السلام\",\"cn\":\"Brunei Darussalam\",\"en\":\"文莱达鲁萨兰国\",\"es\":\"Brunei Darussalam\",\"fr\":\"Brunéi Darussalam\",\"ru\":\"Бруней-Даруссалам\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "ID",
                            Names = "{\"ar\":\"إندونيسيا\",\"cn\":\"Indonesia\",\"en\":\"印度尼西亚\",\"es\":\"Indonesia\",\"fr\":\"Indonésie\",\"ru\":\"Индонезия\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "KH",
                            Names = "{\"ar\":\"كمبوديا\",\"cn\":\"Cambodia\",\"en\":\"柬埔寨\",\"es\":\"Camboya\",\"fr\":\"Cambodge\",\"ru\":\"Камбоджа\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "LA",
                            Names = "{\"ar\":\"جمهورية لاو الديمقراطية الشعبية\",\"cn\":\"Lao People's Democratic Republic\",\"en\":\"老挝人民民主共和国\",\"es\":\"República Democrática Popular Lao\",\"fr\":\"République démocratique populaire lao\",\"ru\":\"Лаосская Народно-Демократическая Республика\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "MM",
                            Names = "{\"ar\":\"ميانمار\",\"cn\":\"Myanmar\",\"en\":\"缅甸\",\"es\":\"Myanmar\",\"fr\":\"Myanmar\",\"ru\":\"Мьянма\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "MY",
                            Names = "{\"ar\":\"ماليزيا\",\"cn\":\"Malaysia\",\"en\":\"马来西亚\",\"es\":\"Malasia\",\"fr\":\"Malaisie\",\"ru\":\"Малайзия\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "PH",
                            Names = "{\"ar\":\"الفلبين\",\"cn\":\"Philippines\",\"en\":\"菲律宾\",\"es\":\"Filipinas\",\"fr\":\"Philippines\",\"ru\":\"Филиппины\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "SG",
                            Names = "{\"ar\":\"سنغافورة\",\"cn\":\"Singapore\",\"en\":\"新加坡\",\"es\":\"Singapur\",\"fr\":\"Singapour\",\"ru\":\"Сингапур\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "TH",
                            Names = "{\"ar\":\"تايلند\",\"cn\":\"Thailand\",\"en\":\"泰国\",\"es\":\"Tailandia\",\"fr\":\"Thaïlande\",\"ru\":\"Таиланд\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "TL",
                            Names = "{\"ar\":\"تيمور - ليشتي\",\"cn\":\"Timor-Leste\",\"en\":\"东帝汶\",\"es\":\"Timor-Leste\",\"fr\":\"Timor-Leste\",\"ru\":\"Тимор-Лешти\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "VN",
                            Names = "{\"ar\":\"فييت نام\",\"cn\":\"Viet Nam\",\"en\":\"越南\",\"es\":\"Viet Nam\",\"fr\":\"Viet Nam\",\"ru\":\"Вьетнам\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "AF",
                            Names = "{\"ar\":\"أفغانستان\",\"cn\":\"Afghanistan\",\"en\":\"阿富汗\",\"es\":\"Afganistán\",\"fr\":\"Afghanistan\",\"ru\":\"Афганистан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "AE",
                            Names = "{\"ar\":\"الإمارات العربية المتحدة\",\"cn\":\"United Arab Emirates\",\"en\":\"阿拉伯联合酋长国\",\"es\":\"Emiratos Árabes Unidos\",\"fr\":\"Émirats arabes unis\",\"ru\":\"Объединенные Арабские Эмираты\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "AZ",
                            Names = "{\"ar\":\"أذربيجان\",\"cn\":\"Azerbaijan\",\"en\":\"阿塞拜疆\",\"es\":\"Azerbaiyán\",\"fr\":\"Azerbaïdjan\",\"ru\":\"Азербайджан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "BD",
                            Names = "{\"ar\":\"بنغلاديش\",\"cn\":\"Bangladesh\",\"en\":\"孟加拉国\",\"es\":\"Bangladesh\",\"fr\":\"Bangladesh\",\"ru\":\"Бангладеш\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "KZ",
                            Names = "{\"ar\":\"كازاخستان\",\"cn\":\"Kazakhstan\",\"en\":\"哈萨克斯坦\",\"es\":\"Kazajstán\",\"fr\":\"Kazakhstan\",\"ru\":\"Казахстан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "KG",
                            Names = "{\"ar\":\"قيرغيزستان\",\"cn\":\"Kyrgyzstan\",\"en\":\"吉尔吉斯斯坦\",\"es\":\"Kirguistán\",\"fr\":\"Kirghizistan\",\"ru\":\"Кыргызстан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "TJ",
                            Names = "{\"ar\":\"طاجيكستان\",\"cn\":\"Tajikistan\",\"en\":\"塔吉克斯坦\",\"es\":\"Tayikistán\",\"fr\":\"Tadjikistan\",\"ru\":\"Таджикистан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "TM",
                            Names = "{\"ar\":\"تركمانستان\",\"cn\":\"Turkmenistan\",\"en\":\"土库曼斯坦\",\"es\":\"Turkmenistán\",\"fr\":\"Turkménistan\",\"ru\":\"Туркменистан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "UZ",
                            Names = "{\"ar\":\"أوزبكستان\",\"cn\":\"Uzbekistan\",\"en\":\"乌兹别克斯坦\",\"es\":\"Uzbekistán\",\"fr\":\"Ouzbékistan\",\"ru\":\"Узбекистан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "CY",
                            Names = "{\"ar\":\"قبرص\",\"cn\":\"Cyprus\",\"en\":\"塞浦路斯\",\"es\":\"Chipre\",\"fr\":\"Chypre\",\"ru\":\"Кипр\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "GE",
                            Names = "{\"ar\":\"جورجيا\",\"cn\":\"Georgia\",\"en\":\"格鲁吉亚\",\"es\":\"Georgia\",\"fr\":\"Géorgie\",\"ru\":\"Грузия\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "IQ",
                            Names = "{\"ar\":\"العراق\",\"cn\":\"Iraq\",\"en\":\"伊拉克\",\"es\":\"Iraq\",\"fr\":\"Iraq\",\"ru\":\"Ирак\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "IL",
                            Names = "{\"ar\":\"إسرائيل\",\"cn\":\"Israel\",\"en\":\"以色列\",\"es\":\"Israel\",\"fr\":\"Israël\",\"ru\":\"Израиль\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "JO",
                            Names = "{\"ar\":\"الأردن\",\"cn\":\"Jordan\",\"en\":\"约旦\",\"es\":\"Jordania\",\"fr\":\"Jordanie\",\"ru\":\"Иордания\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "KW",
                            Names = "{\"ar\":\"الكويت\",\"cn\":\"Kuwait\",\"en\":\"科威特\",\"es\":\"Kuwait\",\"fr\":\"Koweït\",\"ru\":\"Кувейт\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "LB",
                            Names = "{\"ar\":\"لبنان\",\"cn\":\"Lebanon\",\"en\":\"黎巴嫩\",\"es\":\"Líbano\",\"fr\":\"Liban\",\"ru\":\"Ливан\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "OM",
                            Names = "{\"ar\":\"عمان\",\"cn\":\"Oman\",\"en\":\"阿曼\",\"es\":\"Omán\",\"fr\":\"Oman\",\"ru\":\"Оман\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "PS",
                            Names = "{\"ar\":\"دولة فلسطين\",\"cn\":\"State of Palestine\",\"en\":\"巴勒斯坦国\",\"es\":\"Estado de Palestina\",\"fr\":\"État de Palestine\",\"ru\":\"Государство Палестина\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "QA",
                            Names = "{\"ar\":\"قطر\",\"cn\":\"Qatar\",\"en\":\"卡塔尔\",\"es\":\"Qatar\",\"fr\":\"Qatar\",\"ru\":\"Катар\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "SA",
                            Names = "{\"ar\":\"المملكة العربية السعودية\",\"cn\":\"Saudi Arabia\",\"en\":\"沙特阿拉伯\",\"es\":\"Arabia Saudita\",\"fr\":\"Arabie saoudite\",\"ru\":\"Саудовская Аравия\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "SY",
                            Names = "{\"ar\":\"الجمهورية العربية السورية\",\"cn\":\"Syrian Arab Republic\",\"en\":\"阿拉伯叙利亚共和国\",\"es\":\"República Árabe Siria\",\"fr\":\"République arabe syrienne\",\"ru\":\"Сирийская Арабская Республика\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "TR",
                            Names = "{\"ar\":\"تركيا\",\"cn\":\"Turkey\",\"en\":\"土耳其\",\"es\":\"Turquía\",\"fr\":\"Turquie\",\"ru\":\"Турция\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "YE",
                            Names = "{\"ar\":\"اليمن\",\"cn\":\"Yemen\",\"en\":\"也门\",\"es\":\"Yemen\",\"fr\":\"Yémen\",\"ru\":\"Йемен\"}",
                            RegionId = 142
                        },
                        new
                        {
                            Code = "AX",
                            Names = "{\"ar\":\"جزر ألاند\",\"cn\":\"Åland Islands\",\"en\":\"奥兰群岛\",\"es\":\"Islas Åland\",\"fr\":\"Îles d’Åland\",\"ru\":\"Аландских островов\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "BA",
                            Names = "{\"ar\":\"البوسنة والهرسك\",\"cn\":\"Bosnia and Herzegovina\",\"en\":\"波斯尼亚和黑塞哥维那\",\"es\":\"Bosnia y Herzegovina\",\"fr\":\"Bosnie-Herzégovine\",\"ru\":\"Босния и Герцеговина\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "ES",
                            Names = "{\"ar\":\"إسبانيا\",\"cn\":\"Spain\",\"en\":\"西班牙\",\"es\":\"España\",\"fr\":\"Espagne\",\"ru\":\"Испания\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "GI",
                            Names = "{\"ar\":\"جبل طارق\",\"cn\":\"Gibraltar\",\"en\":\"直布罗陀\",\"es\":\"Gibraltar\",\"fr\":\"Gibraltar\",\"ru\":\"Гибралтар\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "GR",
                            Names = "{\"ar\":\"اليونان\",\"cn\":\"Greece\",\"en\":\"希腊\",\"es\":\"Grecia\",\"fr\":\"Grèce\",\"ru\":\"Греция\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "HR",
                            Names = "{\"ar\":\"كرواتيا\",\"cn\":\"Croatia\",\"en\":\"克罗地亚\",\"es\":\"Croacia\",\"fr\":\"Croatie\",\"ru\":\"Хорватия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "IT",
                            Names = "{\"ar\":\"إيطاليا\",\"cn\":\"Italy\",\"en\":\"意大利\",\"es\":\"Italia\",\"fr\":\"Italie\",\"ru\":\"Италия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "MK",
                            Names = "{\"ar\":\"مقدونيا الشمالية\",\"cn\":\"North Macedonia\",\"en\":\"北马其顿\",\"es\":\"Macedonia del Norte\",\"fr\":\"Macédoine du Nord\",\"ru\":\"Северная Македония\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "MT",
                            Names = "{\"ar\":\"مالطة\",\"cn\":\"Malta\",\"en\":\"马耳他\",\"es\":\"Malta\",\"fr\":\"Malte\",\"ru\":\"Мальта\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "ME",
                            Names = "{\"ar\":\"الجبل الأسود\",\"cn\":\"Montenegro\",\"en\":\"黑山\",\"es\":\"Montenegro\",\"fr\":\"Monténégro\",\"ru\":\"Черногория\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "PT",
                            Names = "{\"ar\":\"البرتغال\",\"cn\":\"Portugal\",\"en\":\"葡萄牙\",\"es\":\"Portugal\",\"fr\":\"Portugal\",\"ru\":\"Португалия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "SM",
                            Names = "{\"ar\":\"سان مارينو\",\"cn\":\"San Marino\",\"en\":\"圣马力诺\",\"es\":\"San Marino\",\"fr\":\"Saint-Marin\",\"ru\":\"Сан-Марино\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "RS",
                            Names = "{\"ar\":\"صربيا\",\"cn\":\"Serbia\",\"en\":\"塞尔维亚\",\"es\":\"Serbia\",\"fr\":\"Serbie\",\"ru\":\"Сербия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "SI",
                            Names = "{\"ar\":\"سلوفينيا\",\"cn\":\"Slovenia\",\"en\":\"斯洛文尼亚\",\"es\":\"Eslovenia\",\"fr\":\"Slovénie\",\"ru\":\"Словения\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "VA",
                            Names = "{\"ar\":\"الكرسي الرسولي\",\"cn\":\"Holy See\",\"en\":\"教廷\",\"es\":\"Santa Sede\",\"fr\":\"Saint-Siège\",\"ru\":\"Святой Престол\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "AL",
                            Names = "{\"ar\":\"ألبانيا\",\"cn\":\"Albania\",\"en\":\"阿尔巴尼亚\",\"es\":\"Albania\",\"fr\":\"Albanie\",\"ru\":\"Албания\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "AD",
                            Names = "{\"ar\":\"أندورا\",\"cn\":\"Andorra\",\"en\":\"安道尔\",\"es\":\"Andorra\",\"fr\":\"Andorre\",\"ru\":\"Андорра\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "AT",
                            Names = "{\"ar\":\"النمسا\",\"cn\":\"Austria\",\"en\":\"奥地利\",\"es\":\"Austria\",\"fr\":\"Autriche\",\"ru\":\"Австрия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "BE",
                            Names = "{\"ar\":\"بلجيكا\",\"cn\":\"Belgium\",\"en\":\"比利时\",\"es\":\"Bélgica\",\"fr\":\"Belgique\",\"ru\":\"Бельгия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "BG",
                            Names = "{\"ar\":\"بلغاريا\",\"cn\":\"Bulgaria\",\"en\":\"保加利亚\",\"es\":\"Bulgaria\",\"fr\":\"Bulgarie\",\"ru\":\"Болгария\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "BY",
                            Names = "{\"ar\":\"بيلاروس\",\"cn\":\"Belarus\",\"en\":\"白俄罗斯\",\"es\":\"Belarús\",\"fr\":\"Bélarus\",\"ru\":\"Беларусь\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "CZ",
                            Names = "{\"ar\":\"تشيكيا\",\"cn\":\"Czechia\",\"en\":\"捷克\",\"es\":\"Chequia\",\"fr\":\"Tchéquie\",\"ru\":\"Чехия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "HU",
                            Names = "{\"ar\":\"هنغاريا\",\"cn\":\"Hungary\",\"en\":\"匈牙利\",\"es\":\"Hungría\",\"fr\":\"Hongrie\",\"ru\":\"Венгрия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "MD",
                            Names = "{\"ar\":\"جمهورية مولدوفا\",\"cn\":\"Republic of Moldova\",\"en\":\"摩尔多瓦共和国\",\"es\":\"República de Moldova\",\"fr\":\"République de Moldova\",\"ru\":\"Республика Молдова\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "PL",
                            Names = "{\"ar\":\"بولندا\",\"cn\":\"Poland\",\"en\":\"波兰\",\"es\":\"Polonia\",\"fr\":\"Pologne\",\"ru\":\"Польша\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "RO",
                            Names = "{\"ar\":\"رومانيا\",\"cn\":\"Romania\",\"en\":\"罗马尼亚\",\"es\":\"Rumania\",\"fr\":\"Roumanie\",\"ru\":\"Румыния\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "RU",
                            Names = "{\"ar\":\"الاتحاد الروسي\",\"cn\":\"Russian Federation\",\"en\":\"俄罗斯联邦\",\"es\":\"Federación de Rusia\",\"fr\":\"Fédération de Russie\",\"ru\":\"Российская Федерация\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "SK",
                            Names = "{\"ar\":\"سلوفاكيا\",\"cn\":\"Slovakia\",\"en\":\"斯洛伐克\",\"es\":\"Eslovaquia\",\"fr\":\"Slovaquie\",\"ru\":\"Словакия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "UA",
                            Names = "{\"ar\":\"أوكرانيا\",\"cn\":\"Ukraine\",\"en\":\"乌克兰\",\"es\":\"Ucrania\",\"fr\":\"Ukraine\",\"ru\":\"Украина\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "DK",
                            Names = "{\"ar\":\"الدانمرك\",\"cn\":\"Denmark\",\"en\":\"丹麦\",\"es\":\"Dinamarca\",\"fr\":\"Danemark\",\"ru\":\"Дания\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "EE",
                            Names = "{\"ar\":\"إستونيا\",\"cn\":\"Estonia\",\"en\":\"爱沙尼亚\",\"es\":\"Estonia\",\"fr\":\"Estonie\",\"ru\":\"Эстония\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "FI",
                            Names = "{\"ar\":\"فنلندا\",\"cn\":\"Finland\",\"en\":\"芬兰\",\"es\":\"Finlandia\",\"fr\":\"Finlande\",\"ru\":\"Финляндия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "FO",
                            Names = "{\"ar\":\"جزر فايرو\",\"cn\":\"Faroe Islands\",\"en\":\"法罗群岛\",\"es\":\"Islas Feroe\",\"fr\":\"Îles Féroé\",\"ru\":\"Фарерские острова\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "GB",
                            Names = "{\"ar\":\"المملكة المتحدة لبريطانيا العظمى وآيرلندا الشمالية\",\"cn\":\"United Kingdom of Great Britain and Northern Ireland\",\"en\":\"大不列颠及北爱尔兰联合王国\",\"es\":\"Reino Unido de Gran Bretaña e Irlanda del Norte\",\"fr\":\"Royaume-Uni de Grande-Bretagne et d’Irlande du Nord\",\"ru\":\"Соединенное Королевство Великобритании и Северной Ирландии\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "IM",
                            Names = "{\"ar\":\"جزيرة مان\",\"cn\":\"Isle of Man\",\"en\":\"马恩岛\",\"es\":\"Isla de Man\",\"fr\":\"Île de Man\",\"ru\":\"Остров Мэн\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "IE",
                            Names = "{\"ar\":\"آيرلندا\",\"cn\":\"Ireland\",\"en\":\"爱尔兰\",\"es\":\"Irlanda\",\"fr\":\"Irlande\",\"ru\":\"Ирландия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "IS",
                            Names = "{\"ar\":\"آيسلندا\",\"cn\":\"Iceland\",\"en\":\"冰岛\",\"es\":\"Islandia\",\"fr\":\"Islande\",\"ru\":\"Исландия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "LT",
                            Names = "{\"ar\":\"ليتوانيا\",\"cn\":\"Lithuania\",\"en\":\"立陶宛\",\"es\":\"Lituania\",\"fr\":\"Lituanie\",\"ru\":\"Литва\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "LV",
                            Names = "{\"ar\":\"لاتفيا\",\"cn\":\"Latvia\",\"en\":\"拉脱维亚\",\"es\":\"Letonia\",\"fr\":\"Lettonie\",\"ru\":\"Латвия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "NO",
                            Names = "{\"ar\":\"النرويج\",\"cn\":\"Norway\",\"en\":\"挪威\",\"es\":\"Noruega\",\"fr\":\"Norvège\",\"ru\":\"Норвегия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "SJ",
                            Names = "{\"ar\":\"جزيرتي سفالبارد وجان مايِن\",\"cn\":\"Svalbard and Jan Mayen Islands\",\"en\":\"斯瓦尔巴群岛和扬马延岛\",\"es\":\"Islas Svalbard y Jan Mayen\",\"fr\":\"Îles Svalbard-et-Jan Mayen\",\"ru\":\"Острова Свальбард и Ян-Майен\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "SE",
                            Names = "{\"ar\":\"السويد\",\"cn\":\"Sweden\",\"en\":\"瑞典\",\"es\":\"Suecia\",\"fr\":\"Suède\",\"ru\":\"Швеция\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "CH",
                            Names = "{\"ar\":\"سويسرا\",\"cn\":\"Switzerland\",\"en\":\"瑞士\",\"es\":\"Suiza\",\"fr\":\"Suisse\",\"ru\":\"Швейцария\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "DE",
                            Names = "{\"ar\":\"ألمانيا\",\"cn\":\"Germany\",\"en\":\"德国\",\"es\":\"Alemania\",\"fr\":\"Allemagne\",\"ru\":\"Германия\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "FR",
                            Names = "{\"ar\":\"فرنسا\",\"cn\":\"France\",\"en\":\"法国\",\"es\":\"Francia\",\"fr\":\"France\",\"ru\":\"Франция\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "LI",
                            Names = "{\"ar\":\"ليختنشتاين\",\"cn\":\"Liechtenstein\",\"en\":\"列支敦士登\",\"es\":\"Liechtenstein\",\"fr\":\"Liechtenstein\",\"ru\":\"Лихтенштейн\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "LU",
                            Names = "{\"ar\":\"لكسمبرغ\",\"cn\":\"Luxembourg\",\"en\":\"卢森堡\",\"es\":\"Luxemburgo\",\"fr\":\"Luxembourg\",\"ru\":\"Люксембург\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "MC",
                            Names = "{\"ar\":\"موناكو\",\"cn\":\"Monaco\",\"en\":\"摩纳哥\",\"es\":\"Mónaco\",\"fr\":\"Monaco\",\"ru\":\"Монако\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "NL",
                            Names = "{\"ar\":\"هولندا\",\"cn\":\"Netherlands\",\"en\":\"荷兰\",\"es\":\"Países Bajos\",\"fr\":\"Pays-Bas\",\"ru\":\"Нидерланды\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "GG",
                            Names = "{\"ar\":\"غيرنسي\",\"cn\":\"Guernsey\",\"en\":\"格恩西\",\"es\":\"Guernsey\",\"fr\":\"Guernesey\",\"ru\":\"Гернси\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "JE",
                            Names = "{\"ar\":\"جيرسي\",\"cn\":\"Jersey\",\"en\":\"泽西\",\"es\":\"Jersey\",\"fr\":\"Jersey\",\"ru\":\"Джерси\"}",
                            RegionId = 150
                        },
                        new
                        {
                            Code = "–",
                            Names = "{\"ar\":\"سارك\",\"cn\":\"Sark\",\"en\":\"萨克\",\"es\":\"Sark\",\"fr\":\"Sercq\",\"ru\":\"Сарк\"}",
                            RegionId = 150
                        });
                });

            modelBuilder.Entity("HappyTravel.Edo.Data.Locations.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Names = "{\"ar\":\"أفريقيا\",\"cn\":\"非洲\",\"en\":\"Africa\",\"es\":\"África\",\"fr\":\"Afrique\",\"ru\":\"Африка\"}"
                        },
                        new
                        {
                            Id = 19,
                            Names = "{\"ar\":\"الأمريكتان\",\"cn\":\"美洲\",\"en\":\"Americas\",\"es\":\"América\",\"fr\":\"Amérique\",\"ru\":\"Америка\"}"
                        },
                        new
                        {
                            Id = 142,
                            Names = "{\"ar\":\"آسيا\",\"cn\":\"亚洲\",\"en\":\"Asia\",\"es\":\"Asia\",\"fr\":\"Asie\",\"ru\":\"Азия\"}"
                        },
                        new
                        {
                            Id = 150,
                            Names = "{\"ar\":\"أوروبا\",\"cn\":\"欧洲\",\"en\":\"Europe\",\"es\":\"Europa\",\"fr\":\"Europe\",\"ru\":\"Европа\"}"
                        },
                        new
                        {
                            Id = 9,
                            Names = "{\"ar\":\"أوقيانوسيا\",\"cn\":\"大洋洲\",\"en\":\"Oceania\",\"es\":\"Oceanía\",\"fr\":\"Océanie\",\"ru\":\"Океания\"}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
