kind: pipeline
type: docker
name: Test

trigger:
  branch:
    - master
  event:
    include:
      - pull_request

steps:
- name: Test application
  image: registry.happytravel.com/sdk:6.0-focal-sonar
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    HTDC_VAULT_TOKEN:
      from_secret: VAULT_DEV_TOKEN
    HTDC_VAULT_ENDPOINT:
      from_secret: VAULT_DEV_ENDPOINT
    CONSUL_HTTP_ADDR:
      from_secret: CONSUL_DEV_HTTP_ADDR
    CONSUL_HTTP_TOKEN:
      from_secret: CONSUL_DEV_HTTP_TOKEN
    SONAR_PROJECT_KEY:
      from_secret: SONAR_PROJECT_KEY
    SONAR_PROJECT_NAME:
      from_secret: SONAR_PROJECT_NAME
    SONAR_URL:
      from_secret: SONAR_URL
    SONAR_TOKEN:
      from_secret: SONAR_TOKEN
  commands:
    - dotnet sonarscanner begin /k:"$SONAR_PROJECT_KEY" /n:"$SONAR_PROJECT_NAME" /d:sonar.host.url="$SONAR_URL" /d:sonar.login="$SONAR_TOKEN"
    - dotnet build -c Release
    - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
    - dotnet test -c Release


- name: discord-pr
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_PR_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_PR_TOKEN
  when:
    status: [success, failure]

---
kind: pipeline
type: docker
name: Build

trigger:
  branch:
    - master
  event:
    include:
      - push

steps:
- name: Run migrations
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    HTDC_VAULT_TOKEN:
      from_secret: VAULT_DEV_TOKEN
    HTDC_VAULT_ENDPOINT:
      from_secret: VAULT_DEV_ENDPOINT
    CONSUL_HTTP_ADDR:
      from_secret: CONSUL_DEV_HTTP_ADDR
    CONSUL_HTTP_TOKEN:
      from_secret: CONSUL_DEV_HTTP_TOKEN
  commands:
    - cd HappyTravel.Edo.Data
    - dotnet tool restore
    - dotnet ef database update -v

- name: Build docker image EDO & push to repository
  image: plugins/docker
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    VAULT_TOKEN:
      from_secret: VAULT_DEV_TOKEN
    CONSUL_HTTP_TOKEN:
      from_secret: CONSUL_DEV_HTTP_TOKEN
    BUILD_VERSION: ${DRONE_COMMIT_SHA:0:7}
  settings:
    registry: registry.happytravel.com
    repo: registry.happytravel.com/edo
    tags:
      - ${DRONE_COMMIT_SHA:0:7}-DEV
      - ${DRONE_COMMIT_BRANCH}
    force_tag: true
    use_cache: true
    username:
      from_secret: TRAVEL_DOCKER_LOGIN
    password:
      from_secret: TRAVEL_DOCKER_PASSWORD
    build_args_from_env:
      - GITHUB_TOKEN
      - VAULT_TOKEN
      - BUILD_VERSION
      - CONSUL_HTTP_TOKEN

- name: Build docker image Direct API & push to repository
  image: plugins/docker
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    VAULT_TOKEN:
      from_secret: VAULT_DEV_TOKEN
    CONSUL_HTTP_TOKEN:
      from_secret: CONSUL_DEV_HTTP_TOKEN
  settings:
    registry: registry.happytravel.com
    repo: registry.happytravel.com/direct-api
    dockerfile: Dockerfile.DirectApi
    tags:
      - ${DRONE_COMMIT_SHA:0:7}-DIRECT-API-DEV
    force_tag: true
    use_cache: true
    username:
      from_secret: TRAVEL_DOCKER_LOGIN
    password:
      from_secret: TRAVEL_DOCKER_PASSWORD
    build_args_from_env:
      - GITHUB_TOKEN
      - VAULT_TOKEN
      - CONSUL_HTTP_TOKEN

- name: Deploy EDO to DEV
  image: pelotech/drone-helm3:0.14.2
  settings:
    mode: upgrade
    chart: ./Helm/edo
    release: edo
    values_files: ["Helm/edo/values_dev.yaml"]
    namespace: dev
    skip_tls_verify: true
    wait: true
    values: image.tag=${DRONE_COMMIT_SHA:0:7}-DEV
  environment:
    KUBE_API_SERVER:
      from_secret: KUBERNETES_DEV_API
    KUBE_TOKEN:
      from_secret: KUBERNETES_DEV_TOKEN

- name: Deploy DIRECT-API to DEV
  image: pelotech/drone-helm3:0.14.2
  settings:
    mode: upgrade
    chart: ./Helm/direct-api
    release: direct-api
    values_files: ["Helm/direct-api/values_dev.yaml"]
    namespace: dev
    skip_tls_verify: true
    wait: true
    values: image.tag=${DRONE_COMMIT_SHA:0:7}-DIRECT-API-DEV
  environment:
    KUBE_API_SERVER:
      from_secret: KUBERNETES_DEV_API
    KUBE_TOKEN:
      from_secret: KUBERNETES_DEV_TOKEN

- name: discord
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
  when:
    status: [success, failure]

---
kind: pipeline
type: docker
name: production

trigger:
  branches:
    - master
  event:
    - promote
  target:
    - production

steps:
- name: Run migrations
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    HTDC_VAULT_TOKEN:
      from_secret: VAULT_PROD_TOKEN
    HTDC_VAULT_ENDPOINT:
      from_secret: VAULT_PROD_ENDPOINT
    CONSUL_HTTP_ADDR:
      from_secret: CONSUL_PROD_HTTP_ADDR
    CONSUL_HTTP_TOKEN:
      from_secret: CONSUL_PROD_HTTP_TOKEN
  commands:
    - cd HappyTravel.Edo.Data
    - dotnet tool restore
    - dotnet ef database update

- name: Build docker image & push to repository
  image: plugins/docker
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    VAULT_TOKEN:
      from_secret: VAULT_PROD_TOKEN
    CONSUL_HTTP_TOKEN:
      from_secret: CONSUL_PROD_HTTP_TOKEN
    BUILD_VERSION: ${DRONE_COMMIT_SHA:0:7}
  settings:
    registry: registry.happytravel.com
    repo: registry.happytravel.com/edo
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - ${DRONE_COMMIT_BRANCH}
    force_tag: true
    use_cache: true
    username:
      from_secret: TRAVEL_DOCKER_LOGIN
    password:
      from_secret: TRAVEL_DOCKER_PASSWORD
    build_args_from_env:
      - GITHUB_TOKEN
      - VAULT_TOKEN
      - BUILD_VERSION
      - CONSUL_HTTP_TOKEN

- name: Deploy to production
  image: pelotech/drone-helm3:0.14.2
  settings:
    mode: upgrade
    chart: ./Helm/edo
    release: edo
    values_files: ["Helm/edo/values_prod.yaml"]
    namespace: production
    skip_tls_verify: true
    wait: true
    values: image.tag=${DRONE_COMMIT_SHA:0:7}
  environment:
    KUBE_API_SERVER:
      from_secret: KUBERNETES_PROD_API
    KUBE_TOKEN:
      from_secret: KUBERNETES_PROD_TOKEN

- name: discord
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` on production succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` on production failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
  when:
    status: [success, failure]
