version: "3.5"
services:
  edo-api:
    build:
      context: .
      args:
        - GITHUB_TOKEN
    container_name: edo-api
    env_file: dev.env
    expose:
      - "80"
    depends_on:
      - jaeger
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  nginx:
    image: nginx:1.21.0-alpine
    container_name: edo-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - edo-api
    ports:
      - "80:80"
  redis:
    image: redis:6.2.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"