FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG Configuration=Release
ARG VAULT_TOKEN
ENV HTDC_VAULT_TOKEN=$VAULT_TOKEN

WORKDIR /src

COPY . .

WORKDIR /src/HappyTravel.Edo.Data

RUN dotnet tool restore

CMD dotnet ef database update