replicaCount: 1

podAnnotations:
  linkerd.io/inject: enabled

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-production

jaeger:
  collector_host: dns:///jaeger-production-collector-headless.observability:14250

image:
  repository: registry.happytravel.com/direct-api
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false 
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  metrics:
    port: 60000
  healthchecks:
    port: 60001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
  hosts:
    - host: api.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: happytravel-tls
     hosts:
       - api.happytravel.com

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 1
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - direct-api
      topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: true
  podMonitor:
    enabled: true

env:
  ASPNETCORE_ENVIRONMENT: "Production" 
  HTDC_WEBAPI_PORT: "80"
  HTDC_HEALTH_PORT: "60000"
  HTDC_METRICS_PORT: "60001"
  HTDC_VAULT_ENDPOINT: "https://vault.happytravel.com/v1/"
  HTDC_DIRECT_API_SENTRY_ENDPOINT: "https://c9a70dde7c1a47bb9b6db810cd615331@sentry.happytravel.tech/6"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  HTDC_REDIS_HOST: "redis-edo"
  CONSUL_HTTP_ADDR: "https://consul.happytravel.com/"
