{{- $fullName := include "edo.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "edo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-nginx
      protocol: TCP
      name: http
  selector:
    {{- include "edo.selectorLabels" . | nindent 4 }}
