{{- $fullName := include "edo.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "edo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.healthchecks.port }}
      targetPort: http-healthc
      protocol: TCP
      name: healthc
  selector:
    {{- include "edo.selectorLabels" . | nindent 4 }}
