replicaCount: 2

podAnnotations:
  linkerd.io/inject: enabled

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-dev

jaeger:
  collector_host: dns:///jaeger-dev-collector-headless.observability:14250

image:
  repository: registry.happytravel.com/edo
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  grpc:
    port: 5101
  metrics:
    port: 60001
  healthchecks:
    port: 60000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
    - host: edo-dev.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: happytravel-tls
     hosts:
       - edo-dev.happytravel.com

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 1
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - edo
      topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: true
  podMonitor:
    enabled: true

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  HTDC_VAULT_ENDPOINT: "https://vault.dev.happytravel.com/v1/"
  HTDC_EDO_SENTRY_ENDPOINT: "https://db23cc3a191649f39a8d9087ded431f6@sentry.happytravel.com/2"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  HTDC_WEBAPI_PORT: "80"
  HTDC_GRPC_PORT: "5101"
  HTDC_HEALTH_PORT: "60000"
  HTDC_METRICS_PORT: "60001"
  HTDC_REDIS_HOST: "redis-edo"
  CONSUL_HTTP_ADDR: "https://consul-dev.happytravel.com/"
